import { GROUND_Y } from "./managers/SceneManager.js";

/**
 * Project-wide look / feel knobs. Tweak in `?debug`, then hit
 * "Save to params.js" in the Inspector to write `value`s back here.
 *
 * Nested objects become Inspector folders. A leaf is `{ value, ... }`:
 *   - `min` / `max` / `type` / `options` → shown in the GUI
 *   - `value` only → init default, edit in this file
 *   - `debug: false` hides a leaf that would otherwise show
 */
// Backside-sphere skybox shared by the pinned pages (SkySphereScene).
// One set of leaves so the project and about backdrops stay identical.
// Mysterious grayscale: a near-black gradient with a faint gray horizon,
// wobbled stops, and a slow drifting cloud field on top.
const SKY = {
  skyTop: { value: 0x0c0c0e, type: "color", name: "Top" },
  skyMid: { value: 0x202126, type: "color", name: "Mid" },
  skyBottom: { value: 0x040405, type: "color", name: "Bottom" },
  horizonColor: { value: 0x9a9aa4, type: "color", name: "Horizon" },
  horizonHeight: {
    value: 0.42,
    min: 0,
    max: 1,
    step: 0.01,
    name: "Horizon Height",
  },
  horizonWidth: {
    value: 0.28,
    min: 0.02,
    max: 0.8,
    step: 0.01,
    name: "Horizon Width",
  },
  horizonStrength: {
    value: 0.1,
    min: 0,
    max: 2,
    step: 0.01,
    name: "Horizon Glow",
  },
  skySpread: {
    value: 3.2,
    min: 0.5,
    max: 8,
    step: 0.1,
    name: "Vertical Spread",
  },
  skyNoiseScale: {
    value: 2.2,
    min: 0.1,
    max: 8,
    step: 0.1,
    name: "Noise Scale",
  },
  skyNoiseAmount: {
    value: 0.14,
    min: 0,
    max: 0.5,
    step: 0.005,
    name: "Noise Amount",
  },
  skyNoiseSpeed: {
    value: 0.02,
    min: 0,
    max: 0.5,
    step: 0.005,
    name: "Noise Speed",
  },
  skyCloudScale: {
    value: 2.4,
    min: 0.1,
    max: 10,
    step: 0.1,
    name: "Cloud Scale",
  },
  skyCloudAmount: {
    value: 0.4,
    min: 0,
    max: 1.5,
    step: 0.01,
    name: "Cloud Amount",
  },
  skyCloudSpeed: {
    value: 0.015,
    min: 0,
    max: 0.3,
    step: 0.001,
    name: "Cloud Speed",
  },
};

export const params = {
  Transition: {
    pause: { value: false, type: "boolean", name: "Pause" },
    duration: {
      value: 2,
      min: 0.1,
      max: 10,
      step: 0.05,
      name: "Duration",
    },
    progress: { value: 0.44, min: 0, max: 1, step: 0.01, name: "Progress" },
    mode: {
      value: "dual",
      options: { "Dual Field": "dual", "Black Wipe": "black-wipe" },
      name: "Mode",
    },
    Wipe: {
      radius: { value: 64, min: 10, max: 400, step: 1, name: "Radius" },
      rotation: {
        value: 180,
        min: -180,
        max: 180,
        step: 1,
        name: "Rotation",
      },
      edgeColor: { value: 0x1a8a94, type: "color", name: "Edge" },
      ringGlow: { value: 0, min: 0, max: 2, step: 0.01, name: "Ring Glow" },
      noiseScale: {
        value: 0.114,
        min: 0.001,
        max: 1,
        step: 0.001,
        name: "Noise Scale",
      },
      noiseStrength: {
        value: 14.46,
        min: 0,
        max: 20,
        step: 0.01,
        name: "Noise Strength",
      },
      gridScale: {
        value: 0.001,
        min: 0.001,
        max: 1,
        step: 0.001,
        name: "Grid Scale",
      },
      gridPull: {
        value: 0,
        min: 0,
        max: 0.5,
        step: 0.001,
        name: "Grid Pull",
      },
      gridDim: { value: 0.05, min: 0, max: 1, step: 0.01, name: "Grid Dim" },
      radialFalloff: {
        value: 8,
        min: 0.1,
        max: 8,
        step: 0.05,
        name: "Radial Falloff",
      },
      boundaryWidth: {
        value: 1.18,
        min: 0.01,
        max: 4,
        step: 0.01,
        name: "Boundary Width",
      },
      triplanarSharpness: {
        value: 16,
        min: 1,
        max: 80,
        step: 1,
        name: "Triplanar Sharpness",
      },
      originMargin: {
        value: 14.4,
        min: 0,
        max: 20,
        step: 0.1,
        name: "Origin Margin",
      },
    },
  },

  CubeScene: {
    Scene: {
      background: { value: 0x121214, type: "color", name: "Background" },
    },
    Camera: {
      fov: { value: 34, min: 12, max: 90, step: 0.5, name: "FOV" },
      position: { value: [0, 7, 60] },
      lookAt: { value: [0, 0, 0] },
    },
    Glow: {
      glowColor: { value: 0x0000ff, type: "color", name: "Color" },
      glowMin: { value: 0, min: 0, max: 12, step: 0.05, name: "Spill Min" },
      glowMax: { value: 12, min: 0, max: 12, step: 0.05, name: "Spill Max" },
      glowContrast: {
        value: 4,
        min: 0.2,
        max: 4,
        step: 0.05,
        name: "Contrast",
      },
      glowNoiseScale: {
        value: 0.07,
        min: 0.001,
        max: 0.5,
        step: 0.001,
        name: "Noise Scale",
      },
      glowNoiseSpeed: {
        value: 0.075,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Noise Speed",
      },
      shellGlowMin: {
        value: 0,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Shell Min",
      },
      shellGlowMax: {
        value: 2,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Shell Max",
      },
    },
    Lighting: {
      hemiSky: { value: 0xffffff, type: "color", name: "Sky" },
      hemiGround: { value: 0xff8800, type: "color", name: "Ground" },
      hemiIntensity: {
        value: 0.55,
        min: 0,
        max: 5,
        step: 0.05,
        name: "Intensity",
      },
      rimStart: { value: 1, min: 0, max: 1, step: 0.01, name: "Rim Start" },
      rimStrength: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Rim Strength",
      },
      sideGlowPower: {
        value: 2.6,
        min: 0.2,
        max: 6,
        step: 0.05,
        name: "Spill Falloff",
      },
      backLightScale: {
        value: 2,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Screen Back Light",
      },
    },
    Color: {
      colorMin: { value: 0x202020, type: "color", name: "Min" },
      colorMax: { value: 0x202020, type: "color", name: "Max" },
    },
    Shape: {
      roundRadiusMin: {
        value: 0,
        min: 0,
        max: 5,
        step: 0.01,
        name: "Round Min",
      },
      roundRadiusMax: {
        value: 5,
        min: 0,
        max: 5,
        step: 0.01,
        name: "Round Max",
      },
      faceBulge: {
        value: 0.6,
        min: 0,
        max: 0.6,
        step: 0.005,
        name: "Face Bulge",
      },
      depthMin: { value: 0.61, min: 0, max: 4, step: 0.01, name: "Depth Min" },
      depthMax: { value: 3.64, min: 0, max: 4, step: 0.01, name: "Depth Max" },
      cornerInset: {
        value: 0.2,
        min: -2,
        max: 8,
        step: 0.05,
        name: "Wall Push",
      },
    },
    Gaps: {
      gapMin: { value: 0, min: 0, max: 0.8, step: 0.005, name: "Min" },
      gapMax: { value: 0.19, min: 0, max: 0.8, step: 0.005, name: "Max" },
    },
    Layout: {
      floorY: { value: GROUND_Y },
      ceilY: { value: 25 },
      backZ: { value: -44 },
      frontZ: { value: 105 },
      width: { value: 110 },
      targetCellSize: { value: 10 },
      subdivisions: { value: 4 },
      roundSegments: { value: 16 },
      shellPad: { value: 0 },
    },
    SSAO: {
      aoRadius: { value: 4 },
      aoIntensity: { value: 10.5 },
      aoQuality: { value: "Low" },
    },
  },

  PersistentScene: {
    Grid: {
      cols: { value: 34, min: 4, max: 64, step: 1, name: "Columns" },
      rows: { value: 16, min: 4, max: 40, step: 1, name: "Rows" },
      tileSize: { value: 1, min: 0.2, max: 4, step: 0.01, name: "Tile Size" },
      gap: { value: 0.1, min: 0, max: 1, step: 0.005, name: "Gap" },
      cornerRadius: {
        value: 0.1,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Corner Radius",
      },
      depth: { value: 0.4, min: 0.02, max: 1, step: 0.01, name: "Depth" },
      gridX: { value: 0, min: -20, max: 20, step: 0.05, name: "X" },
      gridY: { value: 2, min: -10, max: 20, step: 0.05, name: "Y" },
      gridZ: { value: 0, min: -20, max: 20, step: 0.05, name: "Z" },
    },
    Motion: {
      pushStrength: {
        value: 0.2,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Push",
      },
      pushZ: { value: 2, min: 0, max: 8, step: 0.05, name: "Push Z" },
      hoverLift: { value: 2, min: 0, max: 8, step: 0.05, name: "Hover Lift" },
      rotationStrength: {
        value: 1.8,
        min: 0,
        max: 6,
        step: 0.05,
        name: "Tilt",
      },
      mouseSize: {
        value: 0.25,
        min: 0.02,
        max: 1,
        step: 0.01,
        name: "Mouse Radius",
      },
      idleAmplitude: {
        value: 1,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Idle Drift",
      },
      idleSpeed: {
        value: 1.8,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Idle Speed",
      },
    },
    Glass: {
      displacement: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Displacement",
      },
      chromaticAberration: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "RGB Split",
      },
      refractStrength: {
        value: 0.65,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Refract",
      },
      fresnelIntensity: {
        value: 0.17,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Fresnel",
      },
      fresnelIdle: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Fresnel Idle",
      },
      activeTileColor: {
        value: 0x737373,
        type: "color",
        name: "Active Color",
      },
      activeTileColorAmount: {
        value: 0.45,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Active Color Amt",
      },
      innerRefractEnabled: {
        value: false,
        type: "boolean",
        name: "Inner Refract",
      },
      innerRefract: {
        value: 0.6,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Inner Amount",
      },
    },
    Interface: {
      interfaceAlpha: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Alpha",
      },
      interfaceDensity: {
        value: 0.39,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Density",
      },
      interfaceQuadScale: {
        value: 1.13,
        min: 0.4,
        max: 1.6,
        step: 0.01,
        name: "Scale",
      },
      interfaceZLift: {
        value: 0.12,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Z Pad",
      },
      ringSpeed: {
        value: 0.2,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Ring Speed",
      },
      ringAlpha: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Ring Alpha",
      },
      bracketAlpha: {
        value: 0.66,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Brackets",
      },
      idleBracket: {
        value: 0.4,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Idle Brackets",
      },
      crossAlpha: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Crosshair",
      },
      plusAlpha: {
        value: 0.85,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Center Plus",
      },
      interfaceColor: { value: 0xffffff, type: "color", name: "Color" },
    },
    Whoosh: {
      whooshInterval: {
        value: 5,
        min: 0.5,
        max: 20,
        step: 0.1,
        name: "Interval",
      },
      whooshSpeed: {
        value: 0.65,
        min: 0.05,
        max: 3,
        step: 0.05,
        name: "Speed",
      },
      whooshWidth: {
        value: 0.18,
        min: 0.02,
        max: 0.8,
        step: 0.01,
        name: "Width",
      },
      whooshSmooth: {
        value: 1.2,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Smooth",
      },
      whooshAlpha: {
        value: 0.14,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Alpha",
      },
      whooshFlicker: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Flicker",
      },
      whooshFlickerSpeed: {
        value: 18,
        min: 1,
        max: 40,
        step: 0.5,
        name: "Flicker Speed",
      },
    },
    Overlay: {
      overlayZ: {
        value: 2.4,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Line Depth",
      },
      lineStartZ: {
        value: 0.02,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Line Start Pad",
      },
      labelSize: {
        value: 0.5,
        min: 0.1,
        max: 1.5,
        step: 0.01,
        name: "Label Size",
      },
      lineAlpha: { value: 1, min: 0, max: 1, step: 0.01, name: "Line Alpha" },
      lineReveal: { value: 0, min: 0, max: 1, step: 0.01, name: "Line Reveal" },
    },
    Screen: {
      screenShader: {
        value: "noise-glow",
        options: ["noise-glow", "gradient", "plasma", "solid"],
        name: "Shader",
      },
      screenTransition: {
        value: "strip-datamosh",
        options: ["strip-datamosh", "noise-wipe"],
        name: "Transition",
      },
      screenInset: {
        value: 0.85,
        min: 0.4,
        max: 0.95,
        step: 0.005,
        name: "Inset",
      },
      screenZ: { value: -1.5, min: -8, max: 0, step: 0.05, name: "Z" },
      screenIntro: { value: 0, min: 0, max: 1, step: 0.01, name: "Intro" },
      screenIntroHover: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Intro Hover",
      },
      screenGlowSpeed: {
        value: 0.1,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Glow Speed",
      },
      screenGlowIntensity: {
        value: 0.25,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Glow Intensity",
      },
      screenVideoBrightness: {
        value: 1.2,
        min: 0,
        max: 2,
        step: 0.05,
        name: "Video Brightness",
      },
      screenHoverDisplacement: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Hover Displacement",
      },
      screenHoverIn: {
        value: 1.3,
        min: 0.1,
        max: 4,
        step: 0.05,
        name: "Hover In (s)",
      },
      screenHoverOut: {
        value: 0.8,
        min: 0.1,
        max: 4,
        step: 0.05,
        name: "Hover Out (s)",
      },
    },
    Project: {
      tilesOutDuration: {
        value: 1.5,
        min: 0.1,
        max: 3,
        step: 0.05,
        name: "Tiles Out (s)",
      },
      tilesOutSpread: {
        value: 0.5,
        min: 0,
        max: 6,
        step: 0.1,
        name: "Tiles Out Spread",
      },
    },
    ScreenLight: {
      screenLightIntensity: {
        value: 20,
        min: 0,
        max: 10,
        step: 0.05,
        name: "Intensity",
      },
      screenLightBlur: {
        value: 10,
        min: 0,
        max: 6,
        step: 0.05,
        name: "Blur",
      },
      screenLightColor: { value: 0xffffff, type: "color", name: "Color" },
    },
  },

  ProjectScene: {
    Camera: {
      fov: { value: 34 },
      position: { value: [0, 7, 60] },
      lookAt: { value: [0, 0, 0] },
    },
    Sky: {
      skyTop: { value: 0x262626, type: "color", name: "Top" },
      skyMid: { value: 0x242424, type: "color", name: "Mid" },
      skyBottom: { value: 0x141414, type: "color", name: "Bottom" },
      horizonColor: { value: 0x000000, type: "color", name: "Horizon" },
      horizonHeight: {
        value: 0.48,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Horizon Height",
      },
      horizonWidth: {
        value: 0.28,
        min: 0.02,
        max: 0.8,
        step: 0.01,
        name: "Horizon Width",
      },
      horizonStrength: {
        value: 0.14,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Horizon Glow",
      },
      skySpread: {
        value: 4.2,
        min: 0.5,
        max: 8,
        step: 0.1,
        name: "Vertical Spread",
      },
      skyNoiseScale: {
        value: 2.2,
        min: 0.1,
        max: 8,
        step: 0.1,
        name: "Noise Scale",
      },
      skyNoiseAmount: {
        value: 0.355,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Noise Amount",
      },
      skyNoiseSpeed: {
        value: 0.38,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Noise Speed",
      },
      skyCloudScale: {
        value: 7.5,
        min: 0.1,
        max: 10,
        step: 0.1,
        name: "Cloud Scale",
      },
      skyCloudAmount: {
        value: 1.37,
        min: 0,
        max: 1.5,
        step: 0.01,
        name: "Cloud Amount",
      },
      skyCloudSpeed: {
        value: 0.162,
        min: 0,
        max: 0.3,
        step: 0.001,
        name: "Cloud Speed",
      },
    },
  },

  AboutScene: {
    Camera: {
      fov: { value: 34 },
      position: { value: [0, 7, 60] },
      lookAt: { value: [0, 0, 0] },
    },
    Sky: {
      skyTop: { value: 0x1c1c1c, type: "color", name: "Top" },
      skyMid: { value: 0x050505, type: "color", name: "Mid" },
      skyBottom: { value: 0x000000, type: "color", name: "Bottom" },
      horizonColor: { value: 0x595959, type: "color", name: "Horizon" },
      horizonHeight: {
        value: 0.3,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Horizon Height",
      },
      horizonWidth: {
        value: 0.28,
        min: 0.02,
        max: 0.8,
        step: 0.01,
        name: "Horizon Width",
      },
      horizonStrength: {
        value: 0.1,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Horizon Glow",
      },
      skySpread: {
        value: 3.2,
        min: 0.5,
        max: 8,
        step: 0.1,
        name: "Vertical Spread",
      },
      skyNoiseScale: {
        value: 4.7,
        min: 0.1,
        max: 8,
        step: 0.1,
        name: "Noise Scale",
      },
      skyNoiseAmount: {
        value: 0.455,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Noise Amount",
      },
      skyNoiseSpeed: {
        value: 0.34,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Noise Speed",
      },
      skyCloudScale: {
        value: 0.1,
        min: 0.1,
        max: 10,
        step: 0.1,
        name: "Cloud Scale",
      },
      skyCloudAmount: {
        value: 0.35,
        min: 0,
        max: 1.5,
        step: 0.01,
        name: "Cloud Amount",
      },
      skyCloudSpeed: {
        value: 0,
        min: 0,
        max: 0.3,
        step: 0.001,
        name: "Cloud Speed",
      },
    },
    Wall: {
      // Layout (rebuild-time; edit here)
      wallZ: { value: 10 },
      wallLayers: { value: 3 },
      wallLayerGap: { value: 16 },
      wallAspect: { value: 2.3 },
      wallRowSpacing: { value: 2.6 },
      wallWordCell: { value: 8 },
      wallJitterY: { value: 0.5 },
      wallRevealDuration: { value: 2.5 },
      // Type (live)
      wallFontSize: {
        value: 0.46,
        min: 0.2,
        max: 2,
        step: 0.01,
        name: "Font Size",
      },
      wallLetterSpacing: {
        value: 0.11,
        min: 0,
        max: 0.3,
        step: 0.005,
        name: "Letter Spacing",
      },
      wallWeight: {
        value: -0.08,
        min: -0.08,
        max: 0.1,
        step: 0.001,
        name: "Type Weight",
      },
      // Motion (live)
      wallSpeed: {
        value: 0.42,
        min: 0,
        max: 5,
        step: 0.01,
        name: "Scroll Speed",
      },
      wallSwayAmount: {
        value: 0.31,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Sway Amount",
      },
      wallSwaySpeed: {
        value: 0.1,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Sway Speed",
      },
      // Per-letter shimmer (live): traveling waves fade letters in and out
      wallShimmerAmount: {
        value: 0.73,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Shimmer Dim",
      },
      wallShimmerLift: {
        value: 0.17,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Shimmer Lift",
      },
      wallShimmerScale: {
        value: 0.93,
        min: 0.02,
        max: 2,
        step: 0.01,
        name: "Shimmer Scale",
      },
      wallShimmerSpeed: {
        value: 0.5,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Shimmer Speed",
      },
      wallShimmerLetterPhase: {
        value: 1.75,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Letter Phase",
      },
      // Color / fade (live)
      wallColor: { value: 0x7999c3, type: "color", name: "Text Color" },
      wallDepthFade: {
        value: 0.85,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Depth Fade",
      },
      wallOpacity: {
        value: 0.29,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Opacity",
      },
      wallLayerOpacity: {
        value: 0.46,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Front Opacity",
      },
      wallDepthOpacityFade: {
        value: 0.99,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Depth Opacity Fade",
      },
    },
    Vignette: {
      vignetteStrength: {
        value: 0.34,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Strength",
      },
      vignetteRadius: {
        value: 0.13,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Radius",
      },
      vignetteSmoothness: {
        value: 0.79,
        min: 0.05,
        max: 1.5,
        step: 0.01,
        name: "Smoothness",
      },
    },
  },

  IceScene: {
    Camera: {
      fov: { value: 35 },
      position: { value: [0, 7, 60] },
      lookAt: { value: [0, 0, 0] },
    },
    Scene: {
      fogColor: { value: 0x272b30 },
      fogNear: { value: 60 },
      fogFar: { value: 200 },
      environmentIntensity: { value: 1.05 },
      ambientColor: { value: 0xcdd6de },
      ambientIntensity: { value: 0.1 },
    },
    Ground: {
      uvScale: { value: 30 },
      parallaxScale: { value: 0.5 },
      colorIntensity: { value: 1.4 },
      reflectionStrength: { value: 1 },
      normalScale: { value: 2.2 },
    },
  },
};

export function isParamLeaf(node) {
  return Boolean(node) && typeof node === "object" && "value" in node;
}

export function isDebugParam(node) {
  if (!isParamLeaf(node) || node.debug === false) return false;
  if (node.debug === true) return true;
  return node.type != null || node.min != null || node.options != null;
}

export function paramValues(group) {
  const out = {};
  if (!group) return out;
  for (const [key, node] of Object.entries(group)) {
    if (isParamLeaf(node)) out[key] = node.value;
    else if (node && typeof node === "object")
      Object.assign(out, paramValues(node));
  }
  return out;
}
