import { GROUND_Y } from "./managers/SceneManager.js";

/**
 * Project-wide look / feel knobs. Tweak in `?debug`, then hit
 * "Save to params.js" in the Inspector to write `value`s back here.
 *
 * Nested objects become Inspector folders. A leaf is `{ value, ... }`:
 *   - `min` / `max` / `type` / `options` → shown in the GUI
 *   - `value` only → init default, edit in this file
 *   - `debug: false` hides a leaf that would otherwise show
 */
// Backside-sphere skybox shared by the pinned pages (SkySphereScene).
// One set of leaves so the project and about backdrops stay identical.
// Mysterious grayscale: a near-black gradient with a faint gray horizon,
// wobbled stops, and a slow drifting cloud field on top.
const SKY = {
  skyTop: { value: 0x0c0c0e, type: "color", name: "Top" },
  skyMid: { value: 0x202126, type: "color", name: "Mid" },
  skyBottom: { value: 0x040405, type: "color", name: "Bottom" },
  horizonColor: { value: 0x9a9aa4, type: "color", name: "Horizon" },
  horizonHeight: {
    value: 0.42,
    min: 0,
    max: 1,
    step: 0.01,
    name: "Horizon Height",
  },
  horizonWidth: {
    value: 0.28,
    min: 0.02,
    max: 0.8,
    step: 0.01,
    name: "Horizon Width",
  },
  horizonStrength: {
    value: 0.1,
    min: 0,
    max: 2,
    step: 0.01,
    name: "Horizon Glow",
  },
  skySpread: {
    value: 3.2,
    min: 0.5,
    max: 8,
    step: 0.1,
    name: "Vertical Spread",
  },
  skyNoiseScale: {
    value: 2.2,
    min: 0.1,
    max: 8,
    step: 0.1,
    name: "Noise Scale",
  },
  skyNoiseAmount: {
    value: 0.14,
    min: 0,
    max: 0.5,
    step: 0.005,
    name: "Noise Amount",
  },
  skyNoiseSpeed: {
    value: 0.02,
    min: 0,
    max: 0.5,
    step: 0.005,
    name: "Noise Speed",
  },
  skyCloudScale: {
    value: 2.4,
    min: 0.1,
    max: 10,
    step: 0.1,
    name: "Cloud Scale",
  },
  skyCloudAmount: {
    value: 0.4,
    min: 0,
    max: 1.5,
    step: 0.01,
    name: "Cloud Amount",
  },
  skyCloudSpeed: {
    value: 0.015,
    min: 0,
    max: 0.3,
    step: 0.001,
    name: "Cloud Speed",
  },
};

export const params = {
  Rendering: {
    antialias: {
      value: "msaa",
      options: { MSAA: "msaa", FXAA: "fxaa", Off: "off" },
      name: "Anti-aliasing",
    },
  },
  Transition: {
    pause: { value: false, type: "boolean", name: "Pause" },
    progress: { value: 0, min: 0, max: 1, step: 0.01, name: "Progress" },
    mode: {
      value: "dual",
      options: { "Dual Field": "dual", "Black Wipe": "black-wipe" },
      name: "Mode",
    },
    Wipe: {
      radius: { value: 80, min: 10, max: 400, step: 1, name: "Radius" },
      rotation: {
        value: -134,
        min: -180,
        max: 180,
        step: 1,
        name: "Rotation",
      },
      edgeColor: { value: 0xffffff, type: "color", name: "Edge" },
      ringGlow: { value: 2, min: 0, max: 2, step: 0.01, name: "Ring Glow" },
      noiseScale: {
        value: 0.203,
        min: 0.0001,
        max: 1,
        step: 0.001,
        name: "Noise Scale",
      },
      noiseStrength: {
        value: 5.16,
        min: 0,
        max: 20,
        step: 0.01,
        name: "Noise Strength",
      },
      gridScale: {
        value: 0.001,
        min: 0.001,
        max: 1,
        step: 0.001,
        name: "Grid Scale",
      },
      gridPull: {
        value: 0,
        min: 0,
        max: 0.5,
        step: 0.001,
        name: "Grid Pull",
      },
      gridDim: { value: 0, min: 0, max: 1, step: 0.01, name: "Grid Dim" },
      radialFalloff: {
        value: 8,
        min: 0.1,
        max: 8,
        step: 0.05,
        name: "Radial Falloff",
      },
      boundaryWidth: {
        value: 4,
        min: 0.01,
        max: 4,
        step: 0.01,
        name: "Boundary Width",
      },
      edgeSoftness: {
        value: 4,
        min: 0.5,
        max: 4,
        step: 0.1,
        name: "Edge Softness (px)",
      },
      originMargin: {
        value: 20,
        min: 0,
        max: 20,
        step: 0.1,
        name: "Origin Margin",
      },
      fadeIn: {
        value: 0.1,
        min: 0,
        max: 0.5,
        step: 0.01,
        name: "Fade In",
      },
      Texture: {
        textureAmount: {
          value: 0,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Texture Blend",
        },
        textureScale: {
          value: 0.1,
          min: 0.1,
          max: 2,
          step: 0.01,
          name: "Scale",
        },
        textureStretch: {
          value: 1.8,
          min: 0.5,
          max: 4,
          step: 0.05,
          name: "Stretch",
        },
        textureAngle: {
          value: 35,
          min: -180,
          max: 180,
          step: 1,
          name: "Angle",
        },
        textureVariation: {
          value: 0,
          min: 0,
          max: 10,
          step: 0.01,
          name: "Variation",
        },
        textureImage: { value: "", type: "image", name: "Preview Image…" },
      },
      Digital: {
        digitalAmount: {
          value: 1,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Digital Amount",
        },
        digitalCellSize: {
          value: 0.5,
          min: 0.5,
          max: 8,
          step: 0.1,
          name: "World Cell Size",
        },
        digitalInk: {
          value: 1,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Interface Detail",
        },
        digitalPlaneAngle: {
          value: 15,
          min: -180,
          max: 180,
          step: 0.1,
          name: "World Plane Angle",
        },
        digitalDeformation: {
          value: 0.98,
          min: 0,
          max: 4,
          step: 0.01,
          name: "Square Deformation",
        },
        digitalSquareSize: {
          value: 0.48,
          min: 0.15,
          max: 0.48,
          step: 0.01,
          name: "Square Size",
        },
        digitalBandWidth: {
          value: 0.2,
          min: 0.006,
          max: 0.2,
          step: 0.001,
          name: "Detail Band",
        },
        digitalMarkerDensity: {
          value: 0.43,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Marker Density",
        },
        digitalScanCycles: {
          value: 24.5,
          min: 0,
          max: 40,
          step: 0.5,
          name: "Scan Cycles",
        },
      },
    },
    Lighting: {
      lightingEnabled: { value: true, type: "boolean", name: "Enabled" },
      lightColor: { value: 0xffffff, type: "color", name: "Color" },
      lightIntensity: {
        value: 0.48,
        min: 0,
        max: 4,
        step: 0.01,
        name: "Intensity",
      },
      lightWidth: {
        value: 0.05,
        min: 0.005,
        max: 0.3,
        step: 0.001,
        name: "Front Width",
      },
      lightHeight: {
        value: 8.3,
        min: -20,
        max: 40,
        step: 0.1,
        name: "Source Height",
      },
      lightDiffuse: {
        value: 1.85,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Diffuse",
      },
      lightWrap: {
        value: 0.99,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Wrap",
      },
      lightSpecular: {
        value: 2.46,
        min: 0,
        max: 4,
        step: 0.01,
        name: "Specular",
      },
      lightShininess: {
        value: 256,
        min: 1,
        max: 256,
        step: 1,
        name: "Shininess",
      },
      lightRim: {
        value: 1.51,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Rim",
      },
    },
  },

  CubeScene: {
    Scene: {
      background: { value: 0x121214, type: "color", name: "Background" },
    },
    Particles: {
      glyphEnabled: { value: true, type: "boolean", name: "Enabled" },
      glyphCount: { value: 199, min: 0, max: 1000, step: 1, name: "Count" },
      glyphLifetime: {
        value: 14,
        min: 1,
        max: 40,
        step: 0.5,
        name: "Lifetime (s)",
      },
      glyphLifetimeVariation: {
        value: 0.65,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Lifetime Variation",
      },
      glyphDelay: {
        value: 1,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Respawn Delay (s)",
      },
      glyphFadeIn: {
        value: 1.5,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Fade In (s)",
      },
      glyphFadeOut: {
        value: 2,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Fade Out (s)",
      },
      glyphSize: { value: 0.45, min: 0.1, max: 3, step: 0.05, name: "Size" },
      glyphSizeVariation: {
        value: 0.21,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Size Variation",
      },
      glyphColor: { value: 0x246bff, type: "color", name: "Color" },
      glyphOpacity: {
        value: 0.34,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Opacity",
      },
      glyphSpeed: {
        value: 0.95,
        min: 0,
        max: 3,
        step: 0.05,
        name: "Time Scale",
      },
      glyphOrigin: {
        value: [7, -2, 1],
        type: "vector",
        min: -100,
        max: 100,
        step: 0.5,
        name: "Emitter Center",
      },
      glyphBounds: {
        value: [85, 20, 78],
        type: "vector",
        min: 0,
        max: 150,
        step: 1,
        name: "Emitter Size",
      },
      glyphVelocity: {
        value: [0.07, 0.6, 0],
        type: "vector",
        min: -3,
        max: 3,
        step: 0.01,
        name: "Velocity",
      },
      glyphDrift: {
        value: 0,
        min: 0,
        max: 5,
        step: 0.05,
        name: "Float Amount",
      },
      glyphDriftSpeed: {
        value: 0.4,
        min: 0,
        max: 3,
        step: 0.05,
        name: "Float Speed",
      },
      glyphRotationSpeed: {
        value: 0.22,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Rotation Speed",
      },
      glyphRotationAmount: {
        value: 0,
        min: 0,
        max: 180,
        step: 1,
        name: "Rotation Amount (deg)",
      },
      glyphInterval: {
        value: 0.75,
        min: 0.1,
        max: 4,
        step: 0.05,
        name: "Symbol Interval (s)",
      },
      glyphIntervalVariation: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Interval Variation",
      },
      glyphGlow: {
        value: 1.95,
        min: 0,
        max: 4,
        step: 0.01,
        name: "Glow Strength",
      },
      glyphGlowRadius: {
        value: 0.61,
        min: 0.01,
        max: 1,
        step: 0.01,
        name: "Glow Radius",
      },
    },
    Camera: {
      fov: { value: 34, min: 12, max: 90, step: 0.5, name: "Desktop FOV" },
      fovPortrait: {
        value: 62,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Portrait FOV",
      },
      fovLandscape: {
        value: 46,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Landscape FOV",
      },
      position: { value: [0, 7, 60] },
      lookAt: { value: [0, 0, 0] },
    },
    Glow: {
      glowColor: { value: 0x246bff, type: "color", name: "Color" },
      glowMin: { value: 0, min: 0, max: 12, step: 0.05, name: "Spill Min" },
      glowMax: { value: 12, min: 0, max: 12, step: 0.05, name: "Spill Max" },
      glowContrast: {
        value: 4,
        min: 0.2,
        max: 4,
        step: 0.05,
        name: "Contrast",
      },
      glowNoiseScale: {
        value: 0.07,
        min: 0.001,
        max: 0.5,
        step: 0.001,
        name: "Noise Scale",
      },
      glowNoiseSpeed: {
        value: 0.075,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Noise Speed",
      },
      shellGlowMin: {
        value: 0,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Shell Min",
      },
      shellGlowMax: {
        value: 2,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Shell Max",
      },
    },
    Shafts: {
      shaftsEnabled: { value: true, type: "boolean", name: "Enabled" },
      shaftIntensity: {
        value: 4.6,
        min: 0,
        max: 20,
        step: 0.05,
        name: "Intensity",
      },
      shaftThreshold: {
        value: 0.145,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Hotspot Threshold",
      },
      shaftSoftness: {
        value: 0.305,
        min: 0.01,
        max: 0.5,
        step: 0.005,
        name: "Threshold Softness",
      },
      shaftReach: { value: 13.5, min: 1, max: 60, step: 0.5, name: "Reach" },
      shaftLength: { value: 9.5, min: 1, max: 120, step: 0.5, name: "Length" },
      shaftStart: { value: 5.9, min: 0, max: 10, step: 0.1, name: "Fade In" },
      shaftBlur: { value: 0, min: 0, max: 2, step: 0.005, name: "Spread" },
      shaftMaxDistance: {
        value: 107,
        min: 10,
        max: 300,
        step: 1,
        name: "Max Distance",
      },
      shaftSteps: { value: 19, min: 4, max: 64, step: 1, name: "Samples" },
      shaftResolution: {
        value: 0.45,
        min: 0.1,
        max: 1,
        step: 0.05,
        name: "Resolution",
      },
      shaftAtlasSize: {
        value: "256",
        options: { "Low (128)": 128, "Balanced (256)": 256, "High (512)": 512 },
        name: "Atlas Size",
      },
    },
    Lighting: {
      hemiSky: { value: 0xffffff, type: "color", name: "Sky" },
      hemiGround: { value: 0xff8800, type: "color", name: "Ground" },
      hemiIntensity: {
        value: 0.3,
        min: 0,
        max: 5,
        step: 0.05,
        name: "Intensity",
      },
      rimStart: { value: 1, min: 0, max: 1, step: 0.01, name: "Rim Start" },
      rimStrength: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Rim Strength",
      },
      sideGlowPower: {
        value: 2.6,
        min: 0.2,
        max: 6,
        step: 0.05,
        name: "Spill Falloff",
      },
      backLightScale: {
        value: 2,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Screen Back Light",
      },
    },
    Color: {
      colorMin: { value: 0x202020, type: "color", name: "Min" },
      colorMax: { value: 0x202020, type: "color", name: "Max" },
    },
    Shape: {
      roundRadiusMin: {
        value: 0,
        min: 0,
        max: 5,
        step: 0.01,
        name: "Round Min",
      },
      roundRadiusMax: {
        value: 5,
        min: 0,
        max: 5,
        step: 0.01,
        name: "Round Max",
      },
      faceBulge: {
        value: 0.6,
        min: 0,
        max: 0.6,
        step: 0.005,
        name: "Face Bulge",
      },
      depthMin: { value: 0.61, min: 0, max: 4, step: 0.01, name: "Depth Min" },
      depthMax: { value: 3.64, min: 0, max: 4, step: 0.01, name: "Depth Max" },
      cornerInset: {
        value: 1,
        min: -2,
        max: 8,
        step: 0.05,
        name: "Wall Push",
      },
    },
    Gaps: {
      gapMin: { value: 0, min: 0, max: 0.8, step: 0.005, name: "Min" },
      gapMax: { value: 0.19, min: 0, max: 0.8, step: 0.005, name: "Max" },
    },
    Layout: {
      floorY: { value: GROUND_Y },
      ceilY: { value: 25 },
      backZ: { value: -44 },
      frontZ: { value: 105 },
      width: { value: 110 },
      targetCellSize: { value: 10 },
      subdivisions: { value: 4 },
      roundSegments: { value: 16 },
      shellPad: { value: 0 },
    },
    SSAO: {
      aoRadius: { value: 4 },
      aoIntensity: { value: 10.5 },
      aoQuality: { value: "Low" },
    },
    Highlight: {
      highlightLift: { value: 0, min: 0, max: 6, step: 0.05, name: "Lift" },
      highlightGlow: { value: 0.4, min: 0, max: 10, step: 0.05, name: "Glow" },
      highlightGap: {
        value: 3.15,
        min: 0,
        max: 4,
        step: 0.05,
        name: "Gap Light",
      },
      highlightDecay: {
        value: 0.5,
        min: 0.002,
        max: 0.5,
        step: 0.001,
        name: "Decay / Frame",
      },
    },
    FlowMap: {
      flowEnabled: { value: true, type: "boolean", name: "Enabled" },
      flowResolution: {
        value: "64",
        options: { "Low (64)": 64, "Balanced (128)": 128, "High (256)": 256 },
        name: "Resolution",
      },
      flowRadius: {
        value: 0.065,
        min: 0.01,
        max: 0.3,
        step: 0.005,
        name: "Brush Radius",
      },
      flowFade: {
        value: 3.25,
        min: 0.05,
        max: 5,
        step: 0.05,
        name: "Fade Speed",
      },
      flowDiffusion: {
        value: 0.98,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Diffusion",
      },
      flowAdvection: {
        value: 2.95,
        min: 0,
        max: 4,
        step: 0.05,
        name: "Advection",
      },
      flowVelocityScale: {
        value: 0.35,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Velocity Scale",
      },
      flowLift: { value: 1.6, min: 0, max: 6, step: 0.05, name: "Lift" },
      flowGlow: { value: 3.15, min: 0, max: 4, step: 0.05, name: "Gap Glow" },
      flowHighlight: {
        value: 0.87,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Feeds Highlight",
      },
    },
  },

  PersistentScene: {
    Grid: {
      cols: { value: 34, min: 4, max: 64, step: 1, name: "Columns" },
      rows: { value: 16, min: 4, max: 40, step: 1, name: "Rows" },
      tileSize: { value: 1, min: 0.2, max: 4, step: 0.01, name: "Tile Size" },
      gap: { value: 0.1, min: 0, max: 1, step: 0.005, name: "Gap" },
      cornerRadius: {
        value: 0.135,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Corner Radius",
      },
      depth: { value: 0.4, min: 0.02, max: 1, step: 0.01, name: "Depth" },
      gridX: { value: 0, min: -20, max: 20, step: 0.05, name: "X" },
      gridY: { value: 2, min: -10, max: 20, step: 0.05, name: "Y" },
      gridZ: { value: 0, min: -20, max: 20, step: 0.05, name: "Z" },
    },
    Motion: {
      mouseSnapRange: {
        value: 1.05,
        min: 0,
        max: 2,
        step: 0.05,
        name: "Mouse Snap Range",
      },
      pushStrength: {
        value: 0.2,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Push",
      },
      pushZ: { value: 2, min: 0, max: 8, step: 0.05, name: "Push Z" },
      hoverLift: { value: 2, min: 0, max: 8, step: 0.05, name: "Hover Lift" },
      rotationStrength: {
        value: 1.8,
        min: 0,
        max: 6,
        step: 0.05,
        name: "Tilt",
      },
      mouseSize: {
        value: 0.25,
        min: 0.02,
        max: 1,
        step: 0.01,
        name: "Mouse Radius",
      },
      idleAmplitude: {
        value: 1,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Idle Drift",
      },
      idleSpeed: {
        value: 1.8,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Idle Speed",
      },
    },
    Glass: {
      enhancedGlassEnabled: {
        value: true,
        type: "boolean",
        name: "Enhanced Glass",
      },
      glassIOR: { value: 2.4, min: 1, max: 2.4, step: 0.01, name: "Glass IOR" },
      glassRoughness: {
        value: 0.14,
        min: 0,
        max: 0.6,
        step: 0.01,
        name: "Glass Roughness",
      },
      glassDistance: {
        value: 9.8,
        min: 0,
        max: 12,
        step: 0.1,
        name: "Backdrop Distance",
      },
      displacement: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Displacement",
      },
      chromaticAberration: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "RGB Split",
      },
      refractStrength: {
        value: 0.65,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Refract",
      },
      fresnelIntensity: {
        value: 0.45,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Fresnel",
      },
      fresnelIdle: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Fresnel Idle",
      },
      activeTileColor: {
        value: 0x808080,
        type: "color",
        name: "Active Color",
      },
      activeTileColorAmount: {
        value: 0.63,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Active Color Amt",
      },
      innerRefractEnabled: {
        value: true,
        type: "boolean",
        name: "Inner Refract",
      },
      innerRefract: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Inner Amount",
      },
    },
    Interface: {
      interfaceAlpha: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Alpha",
      },
      interfaceDensity: {
        value: 0.39,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Density",
      },
      interfaceQuadScale: {
        value: 1.13,
        min: 0.4,
        max: 1.6,
        step: 0.01,
        name: "Scale",
      },
      interfaceZLift: {
        value: 0.12,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Z Pad",
      },
      ringSpeed: {
        value: 0.73,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Ring Speed",
      },
      ringAlpha: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Ring Alpha",
      },
      bracketAlpha: {
        value: 0.66,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Brackets",
      },
      idleBracket: {
        value: 0.4,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Idle Brackets",
      },
      crossAlpha: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Crosshair",
      },
      plusAlpha: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Center Plus",
      },
      interfaceColor: { value: 0xf2f2f2, type: "color", name: "Color" },
    },
    Whoosh: {
      whooshInterval: {
        value: 4.5,
        min: 0.5,
        max: 20,
        step: 0.1,
        name: "Interval",
      },
      whooshSpeed: {
        value: 0.65,
        min: 0.05,
        max: 3,
        step: 0.05,
        name: "Speed",
      },
      whooshWidth: {
        value: 0.3,
        min: 0.02,
        max: 0.8,
        step: 0.01,
        name: "Width",
      },
      whooshSmooth: {
        value: 1.2,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Smooth",
      },
      whooshAlpha: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Alpha",
      },
      whooshFlicker: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Flicker",
      },
      whooshFlickerSpeed: {
        value: 18,
        min: 1,
        max: 40,
        step: 0.5,
        name: "Flicker Speed",
      },
    },
    Overlay: {
      overlayZ: {
        value: 2.4,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Line Depth",
      },
      lineStartZ: {
        value: 0.02,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Line Start Pad",
      },
      labelSize: {
        value: 0.5,
        min: 0.1,
        max: 1.5,
        step: 0.01,
        name: "Label Size",
      },
      lineAlpha: { value: 1, min: 0, max: 1, step: 0.01, name: "Line Alpha" },
      lineReveal: { value: 1, min: 0, max: 1, step: 0.01, name: "Line Reveal" },
    },
    Screen: {
      screenShader: {
        value: "noise-glow",
        options: ["noise-glow", "gradient", "plasma", "solid"],
        name: "Shader",
      },
      screenTransition: {
        value: "strip-datamosh",
        options: ["strip-datamosh", "noise-wipe"],
        name: "Transition",
      },
      screenInset: {
        value: 0.85,
        min: 0.4,
        max: 0.95,
        step: 0.005,
        name: "Inset",
      },
      screenZ: { value: -1.5, min: -8, max: 0, step: 0.05, name: "Z" },
      screenIntro: { value: 0, min: 0, max: 1, step: 0.01, name: "Intro" },
      screenIntroHover: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Intro Hover",
      },
      screenGlowSpeed: {
        value: 0.1,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Glow Speed",
      },
      screenGlowIntensity: {
        value: 0.25,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Glow Intensity",
      },
      screenVideoBrightness: {
        value: 0.6,
        min: 0,
        max: 2,
        step: 0.05,
        name: "Video Brightness",
      },
      screenVideoSaturation: {
        value: 0.8,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Video Saturation",
      },
      screenVideoLift: {
        value: 0,
        min: 0,
        max: 0.4,
        step: 0.01,
        name: "Video Black Lift",
      },
      screenVideoMaxBrightness: {
        value: 1,
        min: 0.4,
        max: 1,
        step: 0.01,
        name: "Video Brightness Limit",
      },
      screenVideoDisplaySaturation: {
        value: 1.3,
        min: 1,
        max: 2,
        step: 0.01,
        name: "Video Display Saturation (no light change)",
      },
      screenVideoDisplayGain: {
        value: 1.1,
        min: 1,
        max: 1.6,
        step: 0.01,
        name: "Video Display Gain (no light change)",
      },
      screenHoverDisplacement: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Hover Displacement",
      },
    },
    // Tiles in/out (Grid/GridCompute.js motion, Grid/GridTile.js dissolve)
    Project: {
      hideDepth: {
        value: 5.5,
        min: 0,
        max: 12,
        step: 0.1,
        name: "Tiles Fall Depth",
      },
      hideRotation: {
        value: 6.28,
        min: 0,
        max: 6.28,
        step: 0.01,
        name: "Tiles Tilt (rad)",
      },
      hideRandomness: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Tiles Tilt Variation",
      },
      hideJitter: {
        value: 0.29,
        min: 0,
        max: 0.5,
        step: 0.01,
        name: "Tiles Timing Jitter",
      },
      hideOvershoot: {
        value: 0.3,
        min: 0,
        max: 3,
        step: 0.05,
        name: "Tiles In Overshoot",
      },
      hideFlash: {
        value: 0.39,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Tiles Rim Glint",
      },
      dissolveStart: {
        value: 0.9,
        min: 0,
        max: 0.9,
        step: 0.01,
        name: "Dissolve Start",
      },
      dissolveCells: {
        value: 2,
        min: 1,
        max: 24,
        step: 1,
        name: "Dissolve Cells",
      },
      dissolveSweep: {
        value: 0.24,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Dissolve Sweep",
      },
      dissolveEdge: {
        value: 0.5,
        min: 0,
        max: 0.5,
        step: 0.01,
        name: "Dissolve Edge Width",
      },
      dissolveGlow: {
        value: 0.7,
        min: 0,
        max: 6,
        step: 0.05,
        name: "Dissolve Edge Glow",
      },
      dissolveColor: {
        value: 0xadadad,
        type: "color",
        name: "Dissolve Edge Color",
      },
      hideFade: {
        value: 0.9,
        min: 0,
        max: 0.99,
        step: 0.01,
        name: "Tiles Fade Out Start",
      },
    },
    Gallery: {
      galleryBars: {
        value: 16,
        min: 2,
        max: 32,
        step: 1,
        name: "Vertical Bands",
      },
      galleryScale: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Band Texture Scale",
      },
      galleryFade: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Band Darkness",
      },
      galleryDarknessPower: {
        value: 1.2,
        min: 0.2,
        max: 4,
        step: 0.05,
        name: "Band Darkness Curve",
      },
      galleryOffset: {
        value: 0.02,
        min: 0,
        max: 0.3,
        step: 0.005,
        name: "First Slice Offset",
      },
      gallerySpread: {
        value: 0.8,
        min: 0,
        max: 0.8,
        step: 0.01,
        name: "Additional Slice Spread",
      },
      galleryRevealDistance: {
        value: 1,
        min: 0.25,
        max: 2,
        step: 0.05,
        name: "Reveal Distance (slides)",
      },
      galleryFlickVelocity: {
        value: 0.4,
        min: 0,
        max: 3,
        step: 0.05,
        name: "Flick Velocity (slides/s)",
      },
      galleryFillBelow: {
        value: 0.55,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Portrait Fill Below (visible)",
      },
      galleryContainBelow: {
        value: 0.92,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Desktop Image Contain Below (visible)",
      },
      galleryBlurRadius: {
        value: 7,
        min: 1,
        max: 24,
        step: 0.5,
        name: "Portrait Blur Radius",
      },
      galleryBlurBrightness: {
        value: 0.45,
        min: 0,
        max: 1.5,
        step: 0.01,
        name: "Portrait Blur Brightness",
      },
      galleryBlurSaturation: {
        value: 1.2,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Portrait Blur Saturation",
      },
      galleryBlurSheen: {
        value: 0.06,
        min: 0,
        max: 0.4,
        step: 0.005,
        name: "Portrait Blur Sheen",
      },
      galleryBlurGrain: {
        value: 0.025,
        min: 0,
        max: 0.15,
        step: 0.005,
        name: "Portrait Blur Grain",
      },
      galleryBlurBrightnessMobile: {
        value: 0.65,
        min: 0,
        max: 1.5,
        step: 0.01,
        name: "Portrait Blur Brightness (mobile)",
      },
      galleryBlurGrainMobile: {
        value: 0,
        min: 0,
        max: 0.15,
        step: 0.005,
        name: "Portrait Blur Grain (mobile)",
      },
      // `<key>Mobile` twins replace their desktop value on the touch experience.
      galleryStyle: {
        value: "frame",
        options: { "Gradient Border": "frame", "Frosted Glass": "glass" },
        name: "Card Style",
      },
      Motion: {
        galleryLerp: { value: 0.27, min: 0.02, max: 1, step: 0.01, name: "Settle Lerp (s)" },
        galleryLerpMobile: { value: 0.22, min: 0.02, max: 1, step: 0.01, name: "Settle Lerp (s, mobile)" },
        galleryDragLerp: { value: 0.1, min: 0.01, max: 0.6, step: 0.005, name: "Drag Lerp (s)" },
        galleryDragLerpMobile: { value: 0.05, min: 0.01, max: 0.6, step: 0.005, name: "Drag Lerp (s, mobile)" },
        galleryDragSensitivity: { value: 1, min: 0.2, max: 3, step: 0.05, name: "Drag Sensitivity" },
        galleryDragSensitivityMobile: { value: 1.15, min: 0.2, max: 3, step: 0.05, name: "Drag Sensitivity (mobile)" },
        galleryScrollSensitivity: { value: 1, min: 0.2, max: 3, step: 0.05, name: "Wheel Sensitivity" },
        gallerySpeedDecay: { value: 0.85, min: 0, max: 0.99, step: 0.01, name: "Speed Decay (per frame)" },
        gallerySpeedDecayMobile: { value: 0.88, min: 0, max: 0.99, step: 0.01, name: "Speed Decay (mobile)" },
        gallerySettleDistance: { value: 0.02, min: 0.001, max: 0.2, step: 0.001, name: "Settled Below (slides)" },
      },
      Card: {
        cardScaleFalloff: { value: 0.12, min: 0, max: 0.5, step: 0.005, name: "Side Scale Falloff" },
        cardScaleFalloffMobile: { value: 0.08, min: 0, max: 0.5, step: 0.005, name: "Side Scale Falloff (mobile)" },
        cardSpeedScale: { value: 0.025, min: 0, max: 0.1, step: 0.001, name: "Speed Shrink" },
        cardSpeedScaleMobile: { value: 0.02, min: 0, max: 0.1, step: 0.001, name: "Speed Shrink (mobile)" },
        cardTilt: { value: 0.18, min: -0.8, max: 0.8, step: 0.01, name: "Side Tilt Y (rad)" },
        cardTiltMobile: { value: 0.12, min: -0.8, max: 0.8, step: 0.01, name: "Side Tilt Y (rad, mobile)" },
        cardSpeedTilt: { value: 0.04, min: -0.2, max: 0.2, step: 0.005, name: "Speed Tilt Y" },
        cardSpeedTiltMobile: { value: 0.03, min: -0.2, max: 0.2, step: 0.005, name: "Speed Tilt Y (mobile)" },
        cardBend: { value: 0.02, min: -0.1, max: 0.1, step: 0.001, name: "Speed Bend" },
        cardBendMobile: { value: 0.015, min: -0.1, max: 0.1, step: 0.001, name: "Speed Bend (mobile)" },
        cardDepth: { value: 0.15, min: 0, max: 1, step: 0.01, name: "Side Depth" },
        cardDepthMobile: { value: 0.1, min: 0, max: 1, step: 0.01, name: "Side Depth (mobile)" },
        cardParallax: { value: 0.06, min: 0, max: 0.2, step: 0.005, name: "Image Parallax" },
        cardParallaxMobile: { value: 0.05, min: 0, max: 0.2, step: 0.005, name: "Image Parallax (mobile)" },
        stillScrollTilt: { value: 0.00006, min: -0.0005, max: 0.0005, step: 0.00001, name: "Detail Scroll Tilt X" },
        stillScrollTiltMobile: { value: 0.00005, min: -0.0005, max: 0.0005, step: 0.00001, name: "Detail Scroll Tilt X (mobile)" },
        stillTiltMax: { value: 0.18, min: 0, max: 0.6, step: 0.01, name: "Detail Tilt Max (rad)" },
      },
      Frame: {
        frameGap: { value: 10, min: 0, max: 48, step: 0.5, name: "Gap (px)" },
        frameGapMobile: { value: 6, min: 0, max: 48, step: 0.5, name: "Gap (px, mobile)" },
        frameWidth: { value: 1.5, min: 0.5, max: 8, step: 0.25, name: "Width (px)" },
        frameWidthMobile: { value: 1.25, min: 0.5, max: 8, step: 0.25, name: "Width (px, mobile)" },
        frameRadius: { value: 6, min: 0, max: 40, step: 0.5, name: "Radius (px)" },
        frameRadiusMobile: { value: 4, min: 0, max: 40, step: 0.5, name: "Radius (px, mobile)" },
        frameGlow: { value: 0.35, min: 0, max: 2, step: 0.01, name: "Inner Glow" },
        frameGlowWidth: { value: 6, min: 0.5, max: 32, step: 0.5, name: "Inner Glow Width (px)" },
        frameGlitch: { value: 0.6, min: 0, max: 2, step: 0.01, name: "Glitch" },
        frameGlitchRate: { value: 9, min: 1, max: 30, step: 0.5, name: "Glitch Rate (/s)" },
        frameAberration: { value: 0.6, min: 0, max: 4, step: 0.05, name: "RGB Split (px)" },
        frameSpeed: { value: 0.12, min: -1, max: 1, step: 0.01, name: "Gradient Speed" },
        frameIntensity: { value: 1, min: 0, max: 2, step: 0.01, name: "Intensity" },
        frameColorA: { value: 0xf2f2f2, type: "color", name: "Color A" },
        frameColorB: { value: 0x8ab4ff, type: "color", name: "Color B" },
        frameColorC: { value: 0xb98cff, type: "color", name: "Color C" },
        frameLerp: { value: 0.22, min: 0.02, max: 1, step: 0.01, name: "Draw Lerp (s)" },
      },
      Glass: {
        glassPadding: { value: 14, min: 0, max: 48, step: 0.5, name: "Padding (px)" },
        glassPaddingMobile: { value: 8, min: 0, max: 48, step: 0.5, name: "Padding (px, mobile)" },
        glassRadius: { value: 18, min: 0, max: 48, step: 0.5, name: "Radius (px)" },
        glassRadiusMobile: { value: 12, min: 0, max: 48, step: 0.5, name: "Radius (px, mobile)" },
        glassBevel: { value: 12, min: 1, max: 48, step: 0.5, name: "Bevel (px)" },
        glassBevelMobile: { value: 8, min: 1, max: 48, step: 0.5, name: "Bevel (px, mobile)" },
        glassRefraction: { value: 18, min: 0, max: 80, step: 0.5, name: "Refraction (px)" },
        glassRefractionMobile: { value: 12, min: 0, max: 80, step: 0.5, name: "Refraction (px, mobile)" },
        glassDispersion: { value: 0.25, min: 0, max: 1, step: 0.01, name: "Dispersion" },
        glassFrost: { value: 0.6, min: 0, max: 1.5, step: 0.01, name: "Frost Brightness" },
        glassTint: { value: 0.04, min: 0, max: 0.4, step: 0.005, name: "Front Tint" },
        glassRim: { value: 0.55, min: 0, max: 1, step: 0.01, name: "Rim Light" },
        glassSheen: { value: 0.07, min: 0, max: 0.4, step: 0.005, name: "Sheen" },
        glassLens: { value: 0.03, min: -0.2, max: 0.2, step: 0.005, name: "Image Lens" },
        glassInScale: { value: 0.85, min: 0.3, max: 1, step: 0.01, name: "In Scale From" },
        glassInRise: { value: 0.25, min: 0, max: 1, step: 0.01, name: "In Rise (heights)" },
        glassInTilt: { value: 0.5, min: -1.5, max: 1.5, step: 0.01, name: "In Tilt X (rad)" },
      },
      Label: {
        cardLabelSize: { value: 11, min: 6, max: 32, step: 0.5, name: "Size (px)" },
        cardLabelSizeMobile: { value: 10, min: 6, max: 32, step: 0.5, name: "Size (px, mobile)" },
        cardLabelInset: { value: 16, min: 0, max: 64, step: 0.5, name: "Inset (px)" },
        cardLabelInsetMobile: { value: 10, min: 0, max: 64, step: 0.5, name: "Inset (px, mobile)" },
        cardLabelOpacity: { value: 0.7, min: 0, max: 1, step: 0.01, name: "Opacity" },
        cardLabelAberration: { value: 1.2, min: 0, max: 4, step: 0.05, name: "RGB Split (px)" },
      },
    },
    ScreenLight: {
      screenLightIntensity: {
        value: 20,
        min: 0,
        max: 10,
        step: 0.05,
        name: "Intensity",
      },
      screenLightBlur: {
        value: 10,
        min: 0,
        max: 6,
        step: 0.05,
        name: "Blur",
      },
      screenLightColor: { value: 0xffffff, type: "color", name: "Color" },
    },
    ScreenShafts: {
      shaftsEnabled: { value: true, type: "boolean", name: "Enabled" },
      shaftIntensity: {
        value: 2.2,
        min: 0,
        max: 10,
        step: 0.05,
        name: "Intensity",
      },
      shaftDensity: {
        value: 0.295,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Haze Density",
      },
      shaftLength: { value: 12, min: 1, max: 60, step: 0.5, name: "Length" },
      shaftFalloff: {
        value: 2.3,
        min: 0.5,
        max: 40,
        step: 0.1,
        name: "Falloff Distance",
      },
      shaftAnisotropy: {
        value: 0.38,
        min: -0.9,
        max: 0.95,
        step: 0.01,
        name: "Forward Scatter",
      },
      shaftConvergence: {
        value: 0.04,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Convergence",
      },
      shaftSoftness: {
        value: 0,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Penumbra",
      },
      shaftTileTransmission: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Tile Transmission",
      },
      shaftDetail: {
        value: 0.54,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Screen Detail",
      },
      shaftSteps: { value: 20, min: 4, max: 64, step: 1, name: "Samples" },
      shaftResolution: {
        value: 0.25,
        min: 0.25,
        max: 1,
        step: 0.05,
        name: "Resolution",
      },
    },
  },

  ProjectScene: {
    Camera: {
      fov: { value: 34, min: 12, max: 90, step: 0.5, name: "Desktop FOV" },
      fovPortrait: {
        value: 54,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Portrait FOV",
      },
      fovLandscape: {
        value: 46,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Landscape FOV",
      },
      position: { value: [0, 7, 60] },
      lookAt: { value: [0, 0, 0] },
    },
    // Cloud vortex backdrop (ProjectScene/vortexSky.js). Its colors are per
    // project: `sky` in src/content/projects.
    Vortex: {
      glowStrength: {
        value: 1.38,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Glow Strength",
      },
      glowFalloff: {
        value: 12.3,
        min: 0.5,
        max: 20,
        step: 0.1,
        name: "Glow Falloff",
      },
      edgeDarken: { value: 1, min: 0, max: 1, step: 0.01, name: "Edge Darken" },
      centerX: { value: 0, min: -0.5, max: 0.5, step: 0.005, name: "Center X" },
      centerY: { value: 0, min: -0.5, max: 0.5, step: 0.005, name: "Center Y" },
      twist: { value: 0.12, min: 0, max: 1.5, step: 0.005, name: "Twist" },
      cloudScale: {
        value: 0.92,
        min: 0.1,
        max: 4,
        step: 0.01,
        name: "Cloud Scale",
      },
      streak: {
        value: 0.2,
        min: 0.05,
        max: 2,
        step: 0.01,
        name: "Depth Stretch",
      },
      coverage: { value: 0.46, min: 0, max: 1, step: 0.005, name: "Coverage" },
      softness: {
        value: 0.14,
        min: 0.01,
        max: 1,
        step: 0.005,
        name: "Softness",
      },
      cloudOpacity: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Opacity",
      },
      fogDensity: {
        value: 0.09,
        min: 0,
        max: 0.5,
        step: 0.001,
        name: "Depth Fog",
      },
      lightOffset: {
        value: 0.25,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Light Offset",
      },
      lightGain: { value: 3.2, min: 0, max: 8, step: 0.05, name: "Light Gain" },
      scrollDepth: {
        value: 3.25,
        min: 0,
        max: 10,
        step: 0.05,
        name: "Scroll Depth",
      },
      headerDim: {
        value: 0.3,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Header Brightness",
      },
      headerDimExit: {
        value: 0.6,
        min: 0.1,
        max: 1.5,
        step: 0.01,
        name: "Header Exit (vh)",
      },
      headerDimDuration: {
        value: 1.6,
        min: 0.1,
        max: 4,
        step: 0.05,
        name: "Header Fade (s)",
      },
      flowSpeed: {
        value: 1.11,
        min: 0,
        max: 3,
        step: 0.005,
        name: "Flow Speed",
      },
      spinSpeed: {
        value: 0.025,
        min: 0,
        max: 0.5,
        step: 0.001,
        name: "Spin Speed",
      },
      warpSpeed: {
        value: 32.7,
        min: 0,
        max: 40,
        step: 0.1,
        name: "Warp Speed",
      },
      warpSpin: { value: 2.3, min: 0, max: 5, step: 0.01, name: "Warp Spin" },
      // How far out the vortex starts its in animation; it zooms to rest as it opens.
      revealZoom: { value: 1.8, min: 1, max: 4, step: 0.01, name: "Reveal Zoom" },
    },
    // Faint streaks riding the cloud spiral (ProjectScene/vortexRibbons.js)
    Ribbons: {
      ribbonEnabled: { value: true, type: "boolean", name: "Enabled" },
      ribbonCount: { value: 160, min: 0, max: 160, step: 1, name: "Count" },
      ribbonLifetime: {
        value: 9,
        min: 1,
        max: 30,
        step: 0.5,
        name: "Lifetime (s)",
      },
      ribbonLifetimeVariation: {
        value: 0.45,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Lifetime Variation",
      },
      ribbonDelay: {
        value: 1.5,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Respawn Delay (s)",
      },
      ribbonFadeIn: {
        value: 1.5,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Fade In (s)",
      },
      ribbonFadeOut: {
        value: 2,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Fade Out (s)",
      },
      ribbonColor: { value: 0xffffff, type: "color", name: "Color" },
      ribbonOpacity: {
        value: 0.16,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Opacity",
      },
      ribbonWidth: {
        value: 2,
        min: 0.25,
        max: 6,
        step: 0.05,
        name: "Width (px)",
      },
      ribbonLength: {
        value: 1.8,
        min: 0.5,
        max: 30,
        step: 0.1,
        name: "Length",
      },
      ribbonNear: {
        value: 2.2,
        min: 0.5,
        max: 20,
        step: 0.1,
        name: "Spawn Near",
      },
      ribbonFar: { value: 39, min: 1, max: 60, step: 0.5, name: "Spawn Far" },
      ribbonSlide: {
        value: 0.35,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Slide Along Spiral",
      },
      ribbonWobble: {
        value: 0.04,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Wobble",
      },
      ribbonFollow: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Follow Cloud Rims",
      },
    },
    // Digital scan pulses racing out of the core (ProjectScene/vortexScan.js)
    Scan: {
      scanEnabled: { value: true, type: "boolean", name: "Enabled" },
      scanColor: { value: 0x9db0d0, type: "color", name: "Color" },
      scanIntensity: {
        value: 0.83,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Intensity",
      },
      scanCloudGlow: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Cloud Glow",
      },
      scanInterval: {
        value: 7,
        min: 1,
        max: 30,
        step: 0.5,
        name: "Interval (s)",
      },
      scanBurst: {
        value: 0.3,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Double Pulse Chance",
      },
      scanDuration: {
        value: 2.6,
        min: 0.5,
        max: 8,
        step: 0.1,
        name: "Duration (s)",
      },
      scanFar: { value: 26, min: 2, max: 80, step: 0.5, name: "Start Depth" },
      scanNear: { value: 0.9, min: 0.3, max: 4, step: 0.05, name: "End Depth" },
      scanTrail: { value: 1.42, min: 0.05, max: 2, step: 0.01, name: "Trail" },
      scanCells: { value: 128, min: 8, max: 160, step: 1, name: "Cells" },
      scanMarkers: {
        value: 0.62,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Marker Density",
      },
      scanGlitch: { value: 0.62, min: 0, max: 1, step: 0.01, name: "Glitch" },
      scanGlitchRate: {
        value: 53,
        min: 1,
        max: 60,
        step: 1,
        name: "Glitch Rate (Hz)",
      },
    },
  },

  AboutScene: {
    Portrait: {
      portraitEnabled: { value: true, type: "boolean", name: "Enabled" },
      Layout: {
        portraitX: {
          value: -0.21,
          min: -0.5,
          max: 0.5,
          step: 0.005,
          name: "Horizontal Position",
        },
        portraitY: {
          value: 0,
          min: -0.5,
          max: 0.5,
          step: 0.005,
          name: "Vertical Position",
        },
        portraitScale: {
          value: 1,
          min: 0.1,
          max: 2.5,
          step: 0.01,
          name: "Scale",
        },
        portraitDepth: {
          value: 0.45,
          min: 0,
          max: 2,
          step: 0.01,
          name: "Depth",
        },
        portraitRotationX: {
          value: 11,
          min: -180,
          max: 180,
          step: 1,
          name: "Rotation X",
        },
        portraitRotationY: {
          value: 15,
          min: -180,
          max: 180,
          step: 1,
          name: "Rotation Y",
        },
        portraitRotationZ: {
          value: 0,
          min: -180,
          max: 180,
          step: 1,
          name: "Rotation Z",
        },
      },
      Dots: {
        portraitPointSize: {
          value: 1.2,
          min: 0.5,
          max: 8,
          step: 0.1,
          name: "Point Size (px)",
        },
        portraitDensity: {
          value: 0.85,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Density",
        },
        portraitResponsiveDensity: {
          value: false,
          type: "boolean",
          name: "Adapt Density to Viewport",
        },
        portraitOpacity: {
          value: 0.74,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Opacity",
        },
        portraitSoftness: {
          value: 0.05,
          min: 0.01,
          max: 1,
          step: 0.01,
          name: "Dot Softness",
        },
        portraitDither: {
          value: 0.78,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Dither Amount",
        },
        portraitDitherScale: {
          value: 4,
          min: 0.5,
          max: 6,
          step: 0.5,
          name: "Dither Pixel Scale",
        },
        portraitNeckFade: {
          value: 0,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Neck Fade",
        },
        portraitEdgeFade: {
          value: 0,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Side Fade",
        },
      },
      Lighting: {
        portraitColor: {
          value: 0xbfbfbf,
          type: "color",
          name: "Highlight Color",
        },
        portraitShadowColor: {
          value: 0xb0b0b0,
          type: "color",
          name: "Shadow Color",
        },
        portraitExposure: {
          value: 6,
          min: 0,
          max: 6,
          step: 0.05,
          name: "Exposure",
        },
        portraitGamma: {
          value: 1.52,
          min: 0.1,
          max: 3,
          step: 0.01,
          name: "Luminance Gamma",
        },
        portraitAmbient: {
          value: 1.69,
          min: 0,
          max: 2,
          step: 0.01,
          name: "Ambient",
        },
        portraitLightStrength: {
          value: 3,
          min: 0,
          max: 3,
          step: 0.01,
          name: "Light Strength",
        },
        portraitLightDirection: {
          value: [2, 2, 0.15],
          type: "vector",
          min: -2,
          max: 2,
          step: 0.05,
          name: "Light Direction",
        },
        portraitRim: {
          value: 0.66,
          min: 0,
          max: 2,
          step: 0.01,
          name: "Rim Light",
        },
        portraitMouseLight: {
          value: 0.95,
          min: 0,
          max: 3,
          step: 0.05,
          name: "Mouse Light",
        },
        portraitHoverStrength: {
          value: 1.25,
          min: 0,
          max: 3,
          step: 0.05,
          name: "Hover Strength",
        },
        portraitHoverRadius: {
          value: 0.22,
          min: 0.04,
          max: 0.6,
          step: 0.01,
          name: "Hover Radius",
        },
      },
      Focus: {
        portraitFocus: {
          value: 0.92,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Focus Depth",
        },
        portraitFocusWidth: {
          value: 0.77,
          min: 0.05,
          max: 1,
          step: 0.01,
          name: "Focus Range",
        },
        portraitDepthBlur: {
          value: 0.55,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Depth Softness",
        },
        portraitDefocusColor: {
          value: 0x47a9e6,
          type: "color",
          name: "Defocus Color",
        },
        portraitGlow: { value: 1.2, min: 0, max: 4, step: 0.05, name: "Glow" },
        portraitGlowRadius: {
          value: 5.4,
          min: 1,
          max: 6,
          step: 0.1,
          name: "Glow Radius",
        },
      },
      Signal: {
        portraitGlitchAmount: {
          value: 0.11,
          min: 0,
          max: 0.15,
          step: 0.001,
          name: "Glitch Displacement",
        },
        portraitGlitchFrequency: {
          value: 0.1,
          min: 0,
          max: 0.5,
          step: 0.005,
          name: "Glitch Frequency",
        },
        portraitGlitchSpeed: {
          value: 6,
          min: 1,
          max: 30,
          step: 1,
          name: "Glitch Rate",
        },
      },
      Motion: {
        portraitRevealScatter: {
          value: 1,
          min: 0,
          max: 3,
          step: 0.05,
          name: "Reveal Scatter",
        },
        portraitMotionAmount: {
          value: 0.0015,
          min: 0,
          max: 0.05,
          step: 0.0005,
          name: "Drift Amount",
        },
        portraitMotionSpeed: {
          value: 0.45,
          min: 0,
          max: 3,
          step: 0.01,
          name: "Drift Speed",
        },
        portraitMouseTilt: {
          value: 12,
          min: 0,
          max: 25,
          step: 0.5,
          name: "Mouse Tilt (deg)",
        },
      },
    },
    Camera: {
      fov: { value: 34, min: 12, max: 90, step: 0.5, name: "Desktop FOV" },
      fovPortrait: {
        value: 54,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Portrait FOV",
      },
      fovLandscape: {
        value: 46,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Landscape FOV",
      },
      position: { value: [0, 7, 60] },
      lookAt: { value: [0, 0, 0] },
    },
    Wall: {
      Focus: {
        wallFocusCoverage: {
          value: 0.22,
          min: 0,
          max: 1,
          step: 0.01,
          name: "Affected Words",
        },
        wallDefocus: {
          value: 1.4,
          min: 0,
          max: 4,
          step: 0.1,
          name: "Depth Softness (px)",
        },
        wallGlow: { value: 1.6, min: 0, max: 5, step: 0.1, name: "Glow" },
        wallGlowRadius: {
          value: 2,
          min: 0.5,
          max: 6,
          step: 0.1,
          name: "Glow Radius (px)",
        },
        wallPulseStrength: {
          value: 2,
          min: 0,
          max: 2,
          step: 0.05,
          name: "Outward Pulse",
        },
        wallPulseInterval: {
          value: 7,
          min: 7,
          max: 30,
          step: 0.5,
          name: "Pulse Interval (s)",
        },
      },
      // Layout (rebuild-time; edit here)
      wallZ: { value: 10 },
      wallLayers: { value: 3 },
      wallLayerGap: { value: 16 },
      wallAspect: { value: 2.3 },
      wallRowSpacing: { value: 2.6 },
      wallWordCell: { value: 8 },
      wallJitterY: { value: 0.5 },
      // Type (live)
      wallFontSize: {
        value: 0.46,
        min: 0.2,
        max: 2,
        step: 0.01,
        name: "Font Size",
      },
      wallLetterSpacing: {
        value: 0.11,
        min: 0,
        max: 0.3,
        step: 0.005,
        name: "Letter Spacing",
      },
      wallWeight: {
        value: -0.08,
        min: -0.08,
        max: 0.1,
        step: 0.001,
        name: "Type Weight",
      },
      // Motion (live)
      wallSpeed: {
        value: 0.42,
        min: 0,
        max: 5,
        step: 0.01,
        name: "Scroll Speed",
      },
      wallSwayAmount: {
        value: 0.31,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Sway Amount",
      },
      wallSwaySpeed: {
        value: 0.1,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Sway Speed",
      },
      // Per-letter shimmer (live): traveling waves fade letters in and out
      wallShimmerAmount: {
        value: 0.73,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Shimmer Dim",
      },
      wallShimmerLift: {
        value: 0.17,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Shimmer Lift",
      },
      wallShimmerScale: {
        value: 0.93,
        min: 0.02,
        max: 2,
        step: 0.01,
        name: "Shimmer Scale",
      },
      wallShimmerSpeed: {
        value: 0.5,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Shimmer Speed",
      },
      wallShimmerLetterPhase: {
        value: 1.75,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Letter Phase",
      },
      // Color / fade (live)
      wallColor: { value: 0x7999c3, type: "color", name: "Text Color" },
      wallDepthFade: {
        value: 0.85,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Depth Fade",
      },
      wallOpacity: {
        value: 0.29,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Opacity",
      },
      wallLayerOpacity: {
        value: 0.46,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Front Opacity",
      },
      wallDepthOpacityFade: {
        value: 0.99,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Depth Opacity Fade",
      },
    },
    Vignette: {
      vignetteStrength: {
        value: 0.34,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Strength",
      },
      vignetteRadius: {
        value: 0.13,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Radius",
      },
      vignetteSmoothness: {
        value: 0.79,
        min: 0.05,
        max: 1.5,
        step: 0.01,
        name: "Smoothness",
      },
    },
  },

  MeadowScene: {
    Fog: {
      fogEnabled: { value: true, type: "boolean", name: "Enabled" },
      fogColor: { value: 0xffffff, type: "color", name: "Color" },
      fogColor2: { value: 0x8f8f8f, type: "color", name: "Billow Color" },
      fogDensity: {
        value: 0.063,
        min: 0,
        max: 0.15,
        step: 0.001,
        name: "Density",
      },
      fogHoleyness: {
        value: 0.58,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Holeyness",
      },
      fogAlpha: { value: 0.45, min: 0, max: 1, step: 0.01, name: "Opacity" },
      fogSpeed: {
        value: 0.35,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Drift Speed",
      },
      fogFrequency: {
        value: 0.011,
        min: 0.005,
        max: 0.2,
        step: 0.001,
        name: "Noise Frequency",
      },
      fogHeightFalloff: {
        value: 0.31,
        min: 0.01,
        max: 1,
        step: 0.01,
        name: "Height Falloff",
      },
      fogBillowHeight: {
        value: 6,
        min: 0,
        max: 20,
        step: 0.1,
        name: "Billow Height",
      },
      fogAmbientStrength: {
        value: 0.345,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Ambient Fill",
      },
      fogLightStrength: {
        value: 0.28,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Screen Light",
      },
      fogMaxDistance: {
        value: 104,
        min: 30,
        max: 300,
        step: 1,
        name: "Max Distance",
      },
      fogSteps: { value: 8, min: 8, max: 48, step: 1, name: "Samples" },
    },
    Rain: {
      rainIntensity: {
        value: 0.95,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Intensity",
      },
      rainColor: { value: 0xadc3cc, type: "color", name: "Color" },
      rainSpeed: { value: 34, min: 8, max: 60, step: 0.5, name: "Fall Speed" },
      rainHeight: { value: 45, min: 20, max: 90, step: 1, name: "Height" },
      rainCellSize: {
        value: 1.8,
        min: 1.5,
        max: 4,
        step: 0.1,
        name: "Spacing",
      },
      rainLength: {
        value: 1.1,
        min: 0.1,
        max: 3,
        step: 0.05,
        name: "Streak Length",
      },
      rainWidth: {
        value: 0.035,
        min: 0.01,
        max: 0.12,
        step: 0.005,
        name: "Streak Width",
      },
      rainOpacity: { value: 0.1, min: 0, max: 1, step: 0.01, name: "Opacity" },
      rainWind: {
        value: 0.29,
        min: -0.4,
        max: 0.4,
        step: 0.01,
        name: "Wind Slant",
      },
      rippleStrength: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Impact Strength",
      },
      rippleRadius: {
        value: 0.65,
        min: 0.1,
        max: 1.5,
        step: 0.05,
        name: "Ripple Radius",
      },
      rippleLifetime: {
        value: 0.9,
        min: 0.2,
        max: 2,
        step: 0.05,
        name: "Ripple Lifetime",
      },
    },
    Roses: {
      roseDensity: {
        value: 0.25,
        min: 0,
        max: 3,
        step: 0.05,
        name: "Trail Density",
      },
      roseScaleMin: {
        value: 1.4,
        min: 0.5,
        max: 8,
        step: 0.1,
        name: "Minimum Scale",
      },
      roseScaleMax: {
        value: 3.7,
        min: 0.5,
        max: 10,
        step: 0.1,
        name: "Maximum Scale",
      },
      roseScatter: {
        value: 2.7,
        min: 0,
        max: 4,
        step: 0.05,
        name: "Trail Scatter",
      },
      roseLeanMax: {
        value: 25,
        min: 0,
        max: 55,
        step: 1,
        name: "Maximum Lean",
      },
      roseVatFps: { value: 30, min: 1, max: 60, step: 1, name: "VAT FPS" },
      roseVatEndFrame: {
        value: 120,
        min: 1,
        max: 168,
        step: 1,
        name: "VAT Hold Frame",
      },
      roseGrowDuration: {
        value: 0.3,
        min: 0.1,
        max: 5,
        step: 0.05,
        name: "Emergence Time",
      },
      roseLifetime: { value: 1, min: 1, max: 60, step: 0.5, name: "Lifetime" },
      roseDegrowDuration: {
        value: 2,
        min: 0.25,
        max: 8,
        step: 0.05,
        name: "Degrow Time",
      },
      roseEmergenceDepth: {
        value: 5.5,
        min: 0,
        max: 15,
        step: 0.1,
        name: "Emergence Depth",
      },
      roseColor1: { value: 0x8246dd, type: "color", name: "Blush" },
      roseColor2: { value: 0x5c61ff, type: "color", name: "Coral" },
      roseColor3: { value: 0xff334f, type: "color", name: "Crimson" },
      roseColor4: { value: 0xff881a, type: "color", name: "Peach" },
      roseColor5: { value: 0xf500d4, type: "color", name: "Lavender" },
      roseRoughness: {
        value: 0.22,
        min: 0.05,
        max: 1,
        step: 0.01,
        name: "Roughness",
      },
      roseLightStrength: {
        value: 1.25,
        min: 0,
        max: 4,
        step: 0.05,
        name: "Screen Light",
      },
      roseLightSmoothing: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Light Normal Smoothing",
      },
      roseLightSoftness: {
        value: 1,
        min: 0.1,
        max: 1,
        step: 0.01,
        name: "Light Softness",
      },
      roseScreenExclusionRadius: {
        value: 0,
        min: 0,
        max: 30,
        step: 0.25,
        name: "Screen Exclusion",
      },
      roseWallExclusionRadius: {
        value: 3.25,
        min: 0,
        max: 30,
        step: 0.25,
        name: "Wall Exclusion",
      },
      roseRippleRadius: {
        value: 8,
        min: 0.25,
        max: 8,
        step: 0.05,
        name: "Ripple Radius",
      },
      roseRippleLifetime: {
        value: 1.2,
        min: 0.2,
        max: 4,
        step: 0.05,
        name: "Ripple Lifetime",
      },
      roseRippleStrength: {
        value: 1.5,
        min: 0,
        max: 1.5,
        step: 0.01,
        name: "Ripple Strength",
      },
      roseRippleFoam: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Ripple Foam",
      },
      roseRippleDelay: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Ripple Timing",
      },
    },
    Tracking: {
      trackingAlpha: { value: 0.45, min: 0, max: 1, step: 0.01, name: "Alpha" },
      trackingRoseChance: {
        value: 0.32,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Rose Spawn Chance",
      },
      trackingRoseAlpha: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Rose Alpha",
      },
      trackingWallCount: {
        value: 11,
        min: 0,
        max: 32,
        step: 1,
        name: "Wall Markers",
      },
      trackingWallAlpha: {
        value: 0.81,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Wall Alpha",
      },
      trackingWallCycle: {
        value: 1.4,
        min: 0.2,
        max: 20,
        step: 0.1,
        name: "Wall Cycle (s)",
      },
      trackingLineAlpha: {
        value: 0.79,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Line Alpha",
      },
      trackingMaxLinks: {
        value: 48,
        min: 0,
        max: 64,
        step: 1,
        name: "Max Links",
      },
      trackingMaxDegree: {
        value: 3,
        min: 1,
        max: 5,
        step: 1,
        name: "Links Per Marker",
      },
      trackingMaxLinkPixels: {
        value: 480,
        min: 80,
        max: 800,
        step: 10,
        name: "Max Link Length",
      },
    },
    Camera: {
      fov: { value: 33.5, min: 12, max: 90, step: 0.5, name: "Desktop FOV" },
      fovPortrait: {
        value: 54,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Portrait FOV",
      },
      fovLandscape: {
        value: 46,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Landscape FOV",
      },
      position: {
        value: [0, 7, 68.5],
        type: "vector",
        min: -150,
        max: 150,
        step: 0.5,
        name: "Position",
      },
      lookAt: {
        value: [0, 0, 0],
        type: "vector",
        min: -100,
        max: 100,
        step: 0.5,
        name: "Look At",
      },
    },
    Wall: {
      wallX: { value: 0, min: -100, max: 100, step: 0.5, name: "X" },
      wallZ: { value: -36.5, min: -100, max: -5, step: 0.5, name: "Z" },
      mobileWallZ: {
        value: -14.5,
        min: -100,
        max: -5,
        step: 0.5,
        name: "Mobile Z",
      },
      mobileWallWidth: {
        value: 63,
        min: 20,
        max: 150,
        step: 1,
        name: "Mobile Width",
      },
      mobileWallHeight: {
        value: 72,
        min: 20,
        max: 150,
        step: 1,
        name: "Mobile Height",
      },
      wallWidth: { value: 153, min: 30, max: 250, step: 1, name: "Width" },
      wallHeight: { value: 54, min: 20, max: 150, step: 1, name: "Height" },
      wallDepth: { value: 10, min: 1, max: 25, step: 0.25, name: "Depth" },
      wallCoverOverscan: {
        value: 1.06,
        min: 1,
        max: 1.5,
        step: 0.01,
        name: "Cover Overscan",
      },
      wallCoverStretch: {
        value: 1.15,
        min: 1,
        max: 2,
        step: 0.01,
        name: "Cover Max Stretch",
      },
      submersion: {
        value: 7.8,
        min: 0,
        max: 18,
        step: 0.1,
        name: "Submersion",
      },
      leafTint: { value: 0x8caaa0, type: "color", name: "Leaf Tint" },
      leafRoughness: {
        value: 0.14,
        min: 0.1,
        max: 1,
        step: 0.01,
        name: "Leaf Roughness",
      },
      leafNormalStrength: {
        value: 1.03,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Leaf Normal",
      },
      leafWindStrength: {
        value: 0.1,
        min: 0,
        max: 0.35,
        step: 0.005,
        name: "Wind Rustle",
      },
      leafWindSpeed: {
        value: 0.9,
        min: 0,
        max: 3,
        step: 0.05,
        name: "Wind Speed",
      },
      leafRainRustle: {
        value: 0.14,
        min: 0,
        max: 0.5,
        step: 0.005,
        name: "Rain Rustle",
      },
      leafRainCoverage: {
        value: 0.56,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Rain Hit Coverage",
      },
    },
    Lighting: {
      background: {
        value: 0x5c5c5c,
        type: "color",
        name: "Overcast Background",
      },
      ambientColor: { value: 0xffffff, type: "color", name: "Ambient Color" },
      ambientIntensity: {
        value: 0.67,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Ambient Intensity",
      },
      plantLightStrength: {
        value: 0.76,
        min: 0,
        max: 4,
        step: 0.01,
        name: "Plant Screen Light",
      },
      plantLightSaturation: {
        value: 0.35,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Leaf Screen Saturation",
      },
      waterLightStrength: {
        value: 0.44,
        min: 0,
        max: 3,
        step: 0.01,
        name: "Water Screen Light",
      },
    },
    Water: {
      waterY: { value: -10.1, min: -25, max: -5, step: 0.1, name: "Level" },
      waterSize: { value: 150, min: 150, max: 600, step: 5, name: "Size" },
      waterColor: { value: 0x13282a, type: "color", name: "Color" },
      waterRoughness: {
        value: 0.34,
        min: 0.04,
        max: 0.9,
        step: 0.01,
        name: "Roughness",
      },
      waveScale: {
        value: 0.019,
        min: 0.005,
        max: 0.2,
        step: 0.001,
        name: "Wave Scale",
      },
      waveStrength: {
        value: 0.17,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Wave Strength",
      },
      waveSpeed: {
        value: 0.037,
        min: 0,
        max: 0.05,
        step: 0.001,
        name: "Wave Speed",
      },
    },
    Shoreline: {
      shoreWidth: { value: 7.1, min: 0.1, max: 10, step: 0.1, name: "Width" },
      shoreStrength: { value: 2, min: 0, max: 2, step: 0.01, name: "Strength" },
      shoreFrequency: {
        value: 6.9,
        min: 1,
        max: 20,
        step: 0.1,
        name: "Ripple Frequency",
      },
      shoreSpeed: {
        value: 0.9,
        min: 0,
        max: 4,
        step: 0.05,
        name: "Ripple Speed",
      },
      foamColor: { value: 0x9c9c9c, type: "color", name: "Foam Color" },
    },
    Reflections: {
      reflectionStrength: {
        value: 1.68,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Strength",
      },
      reflectionDistortion: {
        value: 0.09,
        min: 0,
        max: 0.2,
        step: 0.001,
        name: "Distortion",
      },
      reflectionResolution: {
        value: 0.5,
        min: 0.25,
        max: 1,
        step: 0.05,
        name: "Resolution",
      },
      reflectionInterval: {
        value: 2,
        min: 1,
        max: 4,
        step: 1,
        name: "Frame Interval",
      },
    },
  },
  IceScene: {
    Camera: {
      fov: { value: 35, min: 12, max: 90, step: 0.5, name: "Desktop FOV" },
      fovPortrait: {
        value: 61,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Portrait FOV",
      },
      fovLandscape: {
        value: 46,
        min: 12,
        max: 90,
        step: 0.5,
        name: "Mobile Landscape FOV",
      },
      position: {
        value: [0, 7, 60],
        type: "vector",
        min: -200,
        max: 200,
        step: 0.5,
        name: "Position",
      },
      lookAt: {
        value: [0, 0, 0],
        type: "vector",
        min: -200,
        max: 200,
        step: 0.5,
        name: "Look At",
      },
    },
    Scene: {
      sceneZ: { value: -72, min: -200, max: 80, step: 1, name: "Cave Z" },
      background: { value: 0x000000, type: "color", name: "Background" },
      environmentIntensity: {
        value: 0,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Environment",
      },
      ambientColor: { value: 0x00ddfa, type: "color", name: "Ambient" },
      ambientIntensity: {
        value: 0.29,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Ambient Intensity",
      },
    },
    Cave: {
      caveBodyFill: {
        value: 0,
        min: 0,
        max: 0.5,
        step: 0.01,
        name: "Ice Body",
      },
      caveInnerLayerStrength: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Inner Layer Visibility",
      },
      caveInnerLayerDepth: {
        value: 2.7,
        min: 1,
        max: 4,
        step: 0.05,
        name: "Inner Layer Depth",
      },
      caveInnerLayerBrightness: {
        value: 4,
        min: 0,
        max: 4,
        step: 0.05,
        name: "Inner Layer Brightness",
      },
      caveRoughnessScale: {
        value: 0,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Roughness Detail",
      },
      caveRoughnessBias: {
        value: 0.22,
        min: 0.04,
        max: 1,
        step: 0.01,
        name: "Surface Roughness",
      },
      caveRefractionDistortion: {
        value: 0.25,
        min: 0,
        max: 0.25,
        step: 0.005,
        name: "Buried Distortion",
      },
      caveReflectionStrength: {
        value: 0.08,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Screen Reflection",
      },
      caveReflectionSpread: {
        value: 6,
        min: 1,
        max: 6,
        step: 0.05,
        name: "Reflection Spread",
      },
      caveReflectionBounce: {
        value: 1.55,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Deep Reflection",
      },
      caveFloorRadius: {
        value: 10,
        min: 0,
        max: 20,
        step: 0.5,
        name: "Floor Join Radius",
      },
      caveFloorBlendHeight: {
        value: 0.1,
        min: 0.1,
        max: 8,
        step: 0.1,
        name: "Floor Join Blend",
      },
      caveRidgeStrength: {
        value: 2,
        min: 0,
        max: 2,
        step: 0.05,
        name: "Ridges",
      },
      caveUvRepeatX: { value: 21, min: 1, max: 30, step: 1, name: "UV Across" },
      caveUvRepeatY: { value: 22, min: 1, max: 40, step: 1, name: "UV Along" },
      caveRockCount: { value: 9, min: 0, max: 100, step: 1, name: "Rocks" },
      caveRockScale: {
        value: 0.5,
        min: 0.2,
        max: 2,
        step: 0.05,
        name: "Rock Scale",
      },
      caveFrontZ: { value: 116, min: -80, max: 160, step: 1, name: "Mouth Z" },
      caveLength: { value: 314, min: 40, max: 400, step: 1, name: "Length" },
      caveWidth: { value: 41, min: 8, max: 80, step: 0.5, name: "Width" },
      caveHeight: { value: 43, min: 8, max: 90, step: 0.5, name: "Height" },
      caveTaper: { value: 1, min: 0, max: 1, step: 0.01, name: "Taper" },
      caveBend: { value: 2.2, min: 0, max: 20, step: 0.1, name: "Bend" },
      caveUvScale: {
        value: 0.15,
        min: 0.1,
        max: 8,
        step: 0.05,
        name: "UV Scale",
      },
      caveParallaxScale: {
        value: 0.95,
        min: 0,
        max: 1.5,
        step: 0.01,
        name: "Parallax",
      },
      caveColorIntensity: {
        value: 1.36,
        min: 0,
        max: 3,
        step: 0.02,
        name: "Color",
      },
      caveNormalScale: {
        value: 1.66,
        min: 0,
        max: 3,
        step: 0.02,
        name: "Normals",
      },
    },
    Ground: {
      groundSize: { value: 630, min: 100, max: 1000, step: 10, name: "Size" },
      groundY: { value: -8.4, min: -20, max: 0, step: 0.1, name: "Height" },
      reflectionResolution: {
        value: 0.5,
        min: 0.1,
        max: 1,
        step: 0.05,
        name: "Reflection Resolution",
      },
      reflectionDistortion: {
        value: 0.1,
        min: 0,
        max: 0.1,
        step: 0.001,
        name: "Reflection Distortion",
      },
      reflectionOffsetX: {
        value: 0,
        min: -1,
        max: 1,
        step: 0.01,
        name: "Reflection Shift X",
      },
      reflectionOffsetY: {
        value: 0,
        min: -1,
        max: 1,
        step: 0.01,
        name: "Reflection Shift Y",
      },
      uvScale: { value: 21, min: 1, max: 80, step: 0.5, name: "UV Scale" },
      parallaxScale: {
        value: 1.5,
        min: 0,
        max: 1.5,
        step: 0.01,
        name: "Parallax",
      },
      colorIntensity: { value: 3, min: 0, max: 3, step: 0.02, name: "Color" },
      reflectionStrength: {
        value: 2,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Reflection",
      },
      normalScale: { value: 1.48, min: 0, max: 3, step: 0.02, name: "Normals" },
    },
    Trail: {
      trailEnabled: { value: false, type: "boolean", name: "Enabled" },
      trailResolution: {
        value: "128",
        options: { "Low (128)": 128, "Balanced (256)": 256, "High (512)": 512 },
        name: "Resolution",
      },
      trailUpdateInterval: {
        value: 2,
        min: 1,
        max: 4,
        step: 1,
        name: "Frame Interval",
      },
      trailRadius: {
        value: 0.022,
        min: 0.005,
        max: 0.08,
        step: 0.001,
        name: "Brush Radius",
      },
      trailFade: {
        value: 0.45,
        min: 0.05,
        max: 2,
        step: 0.05,
        name: "Fade Speed",
      },
      trailDiffusion: {
        value: 0.7,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Diffusion",
      },
      trailNoise: {
        value: 0.02,
        min: 0,
        max: 0.02,
        step: 0.001,
        name: "Edge Noise",
      },
      trailStrength: {
        value: 2,
        min: 0,
        max: 2,
        step: 0.01,
        name: "Strength",
      },
      trailColor: { value: 0xf5f5f5, type: "color", name: "Frost Color" },
      trailRoughness: {
        value: 1,
        min: 0.04,
        max: 1,
        step: 0.01,
        name: "Frost Roughness",
      },
    },
    Ripple: {
      rippleSpeed: {
        value: 46,
        min: 1,
        max: 60,
        step: 0.5,
        name: "Speed (u/s)",
      },
      rippleWidth: {
        value: 10,
        min: 0.2,
        max: 10,
        step: 0.1,
        name: "Ring Width",
      },
      rippleFrequency: {
        value: 6,
        min: 0.1,
        max: 6,
        step: 0.05,
        name: "Wave Frequency",
      },
      rippleDecay: {
        value: 0.05,
        min: 0.05,
        max: 4,
        step: 0.05,
        name: "Decay",
      },
      rippleFalloff: {
        value: 0.165,
        min: 0,
        max: 0.3,
        step: 0.005,
        name: "Distance Falloff",
      },
      rippleParallax: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.005,
        name: "Parallax Depth",
      },
      rippleRefraction: {
        value: 1,
        min: 0,
        max: 1,
        step: 0.002,
        name: "Refraction",
      },
      rippleGlow: { value: 1.11, min: 0, max: 4, step: 0.01, name: "Glow" },
      rippleColor: { value: 0xffffff, type: "color", name: "Glow Color" },
      rippleLightIntensity: {
        value: 6,
        min: 0,
        max: 6,
        step: 0.05,
        name: "Light Intensity",
      },
      rippleLightWidth: {
        value: 2,
        min: 2,
        max: 80,
        step: 0.5,
        name: "Light Spread",
      },
      rippleLightColor: { value: 0x00e1ff, type: "color", name: "Light Color" },
    },
    Snow: {
      snowEnabled: { value: true, type: "boolean", name: "Enabled" },
      snowScale: {
        value: 0.018,
        min: 0.002,
        max: 0.3,
        step: 0.001,
        name: "Patch Scale",
      },
      snowFloorCoverage: {
        value: 0.45,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Floor Coverage",
      },
      snowWallCoverage: {
        value: 0.55,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Wall Coverage",
      },
      snowWallHeight: {
        value: 19,
        min: 0,
        max: 30,
        step: 0.5,
        name: "Wall Drift Height",
      },
      snowSlope: {
        value: -0.5,
        min: -0.5,
        max: 0.95,
        step: 0.01,
        name: "Ledge Slope",
      },
      snowSoftness: {
        value: 0.035,
        min: 0.005,
        max: 0.3,
        step: 0.005,
        name: "Edge Softness",
      },
      snowBreakup: {
        value: 0.34,
        min: 0,
        max: 1.5,
        step: 0.01,
        name: "Edge Breakup",
      },
      snowColor: { value: 0xeef6ff, type: "color", name: "Color" },
      snowShadowColor: { value: 0x8fb4cc, type: "color", name: "Shadow Color" },
      snowBrightness: {
        value: 2.6,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Brightness",
      },
      snowRoughness: {
        value: 0.26,
        min: 0.04,
        max: 1,
        step: 0.01,
        name: "Roughness",
      },
      snowBump: { value: 0, min: 0, max: 2, step: 0.01, name: "Bumpiness" },
      snowGrainScale: {
        value: 0.1,
        min: 0.1,
        max: 10,
        step: 0.05,
        name: "Grain Scale",
      },
      snowLightResponse: {
        value: 0.1,
        min: 0,
        max: 5,
        step: 0.01,
        name: "Glitter/Flake Light",
      },
      snowSparkleDensity: {
        value: 9.3,
        min: 0.5,
        max: 30,
        step: 0.1,
        name: "Glitter Density",
      },
      snowSparkleAmount: {
        value: 0.67,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Glitter Amount",
      },
      snowSparkleSize: {
        value: 0.08,
        min: 0.02,
        max: 0.45,
        step: 0.01,
        name: "Glitter Size",
      },
      snowSparkleIntensity: {
        value: 110,
        min: 0,
        max: 200,
        step: 0.5,
        name: "Glitter Intensity",
      },
      snowSparkleSpeed: {
        value: 1.1,
        min: 0,
        max: 10,
        step: 0.05,
        name: "Glitter Twinkle",
      },
      snowSparkleRoughness: {
        value: 0.4,
        min: 0.02,
        max: 1,
        step: 0.01,
        name: "Glitter Roughness",
      },
    },
    Snowfall: {
      flakeEnabled: { value: true, type: "boolean", name: "Enabled" },
      flakeCount: { value: 1023, min: 0, max: 3000, step: 1, name: "Count" },
      flakeLifetime: {
        value: 18,
        min: 1,
        max: 60,
        step: 0.5,
        name: "Lifetime (s)",
      },
      flakeLifetimeVariation: {
        value: 0.4,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Lifetime Variation",
      },
      flakeDelay: {
        value: 0,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Respawn Delay (s)",
      },
      flakeFadeIn: {
        value: 2,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Fade In (s)",
      },
      flakeFadeOut: {
        value: 2,
        min: 0,
        max: 10,
        step: 0.1,
        name: "Fade Out (s)",
      },
      flakeSize: { value: 0.3, min: 0.02, max: 2, step: 0.01, name: "Size" },
      flakeSizeVariation: {
        value: 0.5,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Size Variation",
      },
      flakeColor: { value: 0xffffff, type: "color", name: "Color" },
      flakeOpacity: { value: 0.8, min: 0, max: 1, step: 0.01, name: "Opacity" },
      flakeSpeed: { value: 1, min: 0, max: 3, step: 0.05, name: "Time Scale" },
      flakeOrigin: {
        value: [0, 9, -5],
        type: "vector",
        min: -200,
        max: 200,
        step: 0.5,
        name: "Emitter Center",
      },
      flakeBounds: {
        value: [80, 36, 110],
        type: "vector",
        min: 0,
        max: 300,
        step: 1,
        name: "Emitter Size",
      },
      flakeVelocity: {
        value: [0.3, -1.1, 0],
        type: "vector",
        min: -5,
        max: 5,
        step: 0.01,
        name: "Velocity",
      },
      flakeDrift: {
        value: 1.2,
        min: 0,
        max: 5,
        step: 0.05,
        name: "Sway Amount",
      },
      flakeDriftSpeed: {
        value: 0.35,
        min: 0,
        max: 3,
        step: 0.05,
        name: "Sway Speed",
      },
      flakeSoftness: {
        value: 0.85,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Softness",
      },
      flakeGlisten: { value: 3, min: 0, max: 20, step: 0.1, name: "Glisten" },
      flakeGlistenSpeed: {
        value: 2,
        min: 0,
        max: 10,
        step: 0.05,
        name: "Glisten Speed",
      },
    },
    Material: {
      tint: { value: 0x85adb7, type: "color", name: "Tint" },
      roughnessScale: {
        value: 0.42,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Floor Roughness Detail",
      },
      roughnessBias: {
        value: 0.12,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Floor Roughness",
      },
    },
    Fog: {
      fogEnabled: { value: true, type: "boolean", name: "Enabled" },
      fogBaseY: {
        value: -17.5,
        min: -20,
        max: 20,
        step: 0.5,
        name: "Base Height",
      },
      fogBillowHeight: {
        value: 19.5,
        min: 0,
        max: 30,
        step: 0.5,
        name: "Billow Height",
      },
      fogLightStrength: {
        value: 0.1,
        min: 0,
        max: 8,
        step: 0.05,
        name: "Screen Light",
      },
      fogAmbientStrength: {
        value: 0.169,
        min: 0,
        max: 0.2,
        step: 0.001,
        name: "Ambient Scattering",
      },
      fogColor: { value: 0xe6e6e6, type: "color", name: "Color" },
      fogColor2: { value: 0xaddcff, type: "color", name: "Color 2" },
      fogDensity: {
        value: 0.084,
        min: 0,
        max: 0.12,
        step: 0.001,
        name: "Density",
      },
      fogHoleyness: {
        value: 0.62,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Holeyness",
      },
      fogAlpha: { value: 0.54, min: 0, max: 1, step: 0.01, name: "Alpha" },
      fogHeightFalloff: {
        value: 0.61,
        min: 0,
        max: 1,
        step: 0.01,
        name: "Height Falloff",
      },
      fogSpeed: { value: 0.75, min: 0, max: 2, step: 0.01, name: "Speed" },
      fogFrequency: {
        value: 0.012,
        min: 0.005,
        max: 0.3,
        step: 0.001,
        name: "Frequency",
      },
      fogMaxDistance: {
        value: 76,
        min: 20,
        max: 400,
        step: 1,
        name: "Max Distance",
      },
      fogSteps: { value: 8, min: 8, max: 48, step: 1, name: "Steps" },
    },
    ScreenLight: {
      screenLightScale: {
        value: 0.2,
        min: 0,
        max: 5,
        step: 0.05,
        name: "Front Emission",
      },
      screenBackLightScale: {
        value: 0.4,
        min: 0,
        max: 5,
        step: 0.05,
        name: "Back Emission",
      },
    },
    Lights: {
      backlightColor: { value: 0x4db2ff, type: "color", name: "Back Color" },
      backlightIntensity: {
        value: 875,
        min: 0,
        max: 2000,
        step: 5,
        name: "Back Intensity",
      },
      backlightDistance: {
        value: 180,
        min: 10,
        max: 600,
        step: 1,
        name: "Back Distance",
      },
      backlightPos: {
        value: [-4, 4, -115],
        type: "vector",
        min: -200,
        max: 200,
        step: 0.5,
        name: "Back Pos",
      },
      rimColor: { value: 0x4d9eff, type: "color", name: "Rim Color" },
      rimIntensity: {
        value: 390,
        min: 0,
        max: 800,
        step: 5,
        name: "Rim Intensity",
      },
      rimDistance: {
        value: 83,
        min: 10,
        max: 600,
        step: 1,
        name: "Rim Distance",
      },
      rimPos: {
        value: [0.5, 6.5, 78],
        type: "vector",
        min: -200,
        max: 200,
        step: 0.5,
        name: "Rim Pos",
      },
    },
  },
};

export function isParamLeaf(node) {
  return Boolean(node) && typeof node === "object" && "value" in node;
}

export function isDebugParam(node) {
  if (!isParamLeaf(node) || node.debug === false) return false;
  if (node.debug === true) return true;
  return node.type != null || node.min != null || node.options != null;
}

export function paramValues(group) {
  const out = {};
  if (!group) return out;
  for (const [key, node] of Object.entries(group)) {
    if (isParamLeaf(node)) out[key] = node.value;
    else if (node && typeof node === "object")
      Object.assign(out, paramValues(node));
  }
  return out;
}
